cloudbuild.yaml
https://github.com/GoogleCloudPlatform/click-to-deploy/issues/204
=> Pull gcr.io/cloud-marketplace-tools/k8s/dev image associated with the currently checked out submodule.

k8s/postgresql/README.md
=> Editing PostgreSQL readme

k8s/airflow-operator/README.md, k8s/cassandra/README.md, k8s/elastic-gke-logging/README.md, k8s/elasticsearch/README.md, k8s/grafana/README.md, k8s/influxdb/README.md, k8s/jenkins/README.md, k8s/memcached/README.md, k8s/nginx/README.md, k8s/postgresql/README.md, k8s/prometheus/README.md, k8s/rabbitmq/README.md, k8s/sample-app/README.md, k8s/spark-operator/README.md, k8s/wordpress/README.md
Also, minor formatting of markdown syntax.
=> Fix headings level into readmes

k8s/airflow-operator/README.md, k8s/cassandra/README.md, k8s/elastic-gke-logging/README.md, k8s/elasticsearch/README.md, k8s/grafana/README.md, k8s/influxdb/README.md, k8s/jenkins/README.md, k8s/memcached/README.md, k8s/nginx/README.md, k8s/postgresql/README.md, k8s/prometheus/README.md, k8s/rabbitmq/README.md, k8s/sample-app/README.md, k8s/spark-operator/README.md, k8s/wordpress/README.md
=> Update CRD apply command

k8s/prometheus/manifest/prometheus-statefulset.yaml
=> Remove Prometheus sts limits

cloudbuild-k8s-generator.py, cloudbuild.yaml
This change allows running Cloud Build from CLI following https://github.com/GoogleCloudPlatform/click-to-deploy#manually-run-the-build
=> Replace cluster name and location with variables.

k8s/sample-app/schema.yaml
https://github.com/GoogleCloudPlatform/click-to-deploy/issues/342
=> Sample app schema.yaml has two minimum keys

k8s/cassandra/apptest/tester/tests/basic-suite.yaml, k8s/elastic-gke-logging/apptest/tester/tests/basic-suite.yaml, k8s/elasticsearch/apptest/tester/tests/basic-suite.yaml, k8s/grafana/apptest/tester/tests/basic-suite.yaml, k8s/influxdb/apptest/tester/tests/basic-suite.yaml, k8s/jenkins/apptest/tester/tests/basic-suite.yaml, k8s/memcached/apptest/tester/tests/basic-suite.yaml, k8s/nginx/Makefile, k8s/nginx/apptest/tester/tests/basic-suite.yaml, k8s/postgresql/apptest/tester/tests/basic-suite.yaml, k8s/prometheus/apptest/tester/tests/basic-suite.yaml, k8s/rabbitmq/apptest/tester/tests/basic-suite.yaml, k8s/sample-app/apptest/tester/tests/basic-suite.yaml, k8s/wordpress/apptest/tester/tests/basic-suite.yaml
=> Fix test specs syntax

k8s/postgresql/manifest/application.yaml.template
Internal tracking bug: b/124289936
=> Fix postgres documentation link.

k8s/elastic-gke-logging/Makefile, k8s/wordpress/README.md, k8s/wordpress/deployer/entrypoint.sh, k8s/wordpress/manifest/application.yaml.template, k8s/wordpress/manifest/manifests.yaml.template
Also, use tls secret type instead of generic.
=> [WordPress] Add updating TLS instruction.

cloudbuild-k8s-generator.py, cloudbuild.yaml
=> Remove SonarQube from testing

vm/chef/cookbooks/percona/files/percona-setup, vm/chef/cookbooks/percona/recipes/default.rb
=> percona - put percona-toolkit on the image

k8s/cassandra/Makefile, k8s/cassandra/chart/cassandra/templates/manifests.yaml.template, k8s/cassandra/deployer/Dockerfile, k8s/cassandra/schema.yaml
Also:
* Increase memory request
**Category:**
---
=> [Kubernetes][Cassandra] Add cgroup memory limit support

cloudbuild-k8s-generator.py, cloudbuild.yaml, k8s/spark-operator/apptest/deployer/manifest/tester.yaml.template, k8s/spark-operator/apptest/tester/spark-pi.yaml.template, k8s/spark-operator/apptest/tester/tester.sh, k8s/spark-operator/deployer/Dockerfile
=> Fixed spark-operator app/verify

docker/README.md
=> Add initial docker directory

k8s/airflow-operator/README.md
=> typo in the env variable name SERVICE_ACCOUNT

k8s/wordpress/chart/wordpress/templates/application.yaml.template
=> Fixed typo

Makefile
=> Add help to Makefile

k8s/app.Makefile
**Category:**
---
```
Building app/doctor...
.build/app/dev /scripts/doctor.py
/bin/docker_entrypoint.sh: line 21: /scripts/doctor.py: No such file or directory
```
=> Fix Makefiles (master branch)

k8s/app.Makefile, k8s/app_v2.Makefile
**Category:**
---
```
Building app/doctor...
.build/app/dev /scripts/doctor.py
/bin/docker_entrypoint.sh: line 21: /scripts/doctor.py: No such file or directory
```
=> Fix Makefiles (Managed-Updates-Alpha branch)

k8s/cassandra/Makefile, k8s/elastic-gke-logging/Makefile, k8s/elasticsearch/Makefile, k8s/grafana/Makefile, k8s/influxdb/Makefile, k8s/jenkins/Makefile, k8s/mariadb/Makefile, k8s/memcached/Makefile, k8s/nginx/Makefile, k8s/postgresql/Makefile, k8s/rabbitmq/Makefile, k8s/sonarqube/Makefile, k8s/wordpress/Makefile
Follow-up of https://github.com/GoogleCloudPlatform/click-to-deploy/pull/641#issuecomment-509161769.
=> Split tagging of docker images to the new line into the Makefiles.

vm/chef/cookbooks/solr/attributes/default.rb
**Category:**
---
Bump solr version to 7.7.2
=> Bump solr version to 7.7.2

k8s/elastic-gke-logging/README.md
=> nit: Kibana uses Deployment, not StatefulSet

k8s/cassandra/Makefile, k8s/elastic-gke-logging/Makefile, k8s/elasticsearch/Makefile, k8s/grafana/Makefile, k8s/influxdb/Makefile, k8s/jenkins/Makefile, k8s/mariadb/Makefile, k8s/memcached/Makefile, k8s/nginx/Makefile, k8s/postgresql/Makefile, k8s/rabbitmq/Makefile, k8s/sonarqube/Makefile, k8s/wordpress/Makefile
=> Update kalm tags suffix

k8s/elastic-gke-logging/README.md, k8s/elastic-gke-logging/chart/elastic-gke-logging/templates/fluentd-manifests.yaml, k8s/postgresql/README.md, k8s/wordpress/chart/wordpress/templates/wordpress-manifests.yaml, vm/chef/cookbooks/percona/files/percona-setup, vm/chef/cookbooks/percona/recipes/default.rb, vm/chef/cookbooks/solr/attributes/default.rb
=> Update Managed-Updates-Alpha branch.

docker/README.md
=> Fix a typo

k8s/sonarqube/README.md
**Category:**
---
Editing the readme - wording, typos, etc.
=> Readme edits

k8s/mariadb/README.md, k8s/mariadb/chart/mariadb/templates/application.yaml
**Category:**
---
Readme and `application.yaml` edits for MariaDB
=> Readme edits for MariaDB

vm/chef/cookbooks/singlefs/attributes/default.rb, vm/chef/cookbooks/singlefs/files/apache2-graphite.conf, vm/chef/cookbooks/singlefs/files/singlefs-install, vm/chef/cookbooks/singlefs/files/singlefs-monitoring, vm/chef/cookbooks/singlefs/files/singlefs-validate, vm/chef/cookbooks/singlefs/metadata.rb, vm/chef/cookbooks/singlefs/recipes/default.rb
=> Small changes to Single FS

vm/chef/cookbooks/percona/attributes/default.rb
**Category:**
---
Updated the percona version to use the latest version rather than a static version.
=> Changed percona version from 0.1-7 to latest

vm/chef/cookbooks/piwik/attributes/default.rb, vm/tests/solutions/spec/piwik/index_page_spec.rb
**Category:**
---
Updated the piwik version to use the latest version rather than a static version.
Removed unused variables.
=> Updated piwik to latest and removed unused vars

vm/chef/cookbooks/django/attributes/default.rb, vm/chef/cookbooks/django/recipes/default.rb
=> Updated Django from 1.11.16 to latest

vm/chef/cookbooks/prestashop/attributes/default.rb
=> Bump prestashop to 1.7.6.0

vm/chef/cookbooks/zabbix/attributes/default.rb
=> Bump Zabbix to 4.2

vm/chef/cookbooks/solr/attributes/default.rb
=> Bump solr to 8.2.0

vm/chef/cookbooks/nagios/attributes/default.rb
**Category:**
---
Bumped nagios from 4.4.2 to 4.4.4
=> Bump nagios core to 4.4.4

vm/chef/cookbooks/joomla/attributes/default.rb
=> Bump Joomla to 3.9.10

triggers/k8s/etcd.yaml
=> add etcd trigger yaml

triggers/k8s/consul.yaml
=> Added trigger for Consul

triggers/README.md
=> Update instruction for triggers creation

k8s/consul/Makefile
=> Update container sha256 sums

k8s/etcd/Makefile
=> Change digest of etcd image to production

k8s/consul/Makefile
=> Consul sha updates

docker/README.md, triggers/k8s/mariadb-galera.yaml
=> Added trigger for mariadb-galera, updated docker repo list

k8s/consul/README.md
=> Fix mistypes, image TAG and Consul exorter image path at README file

k8s/mariadb-galera/chart/mariadb-galera/templates/application.yaml
=> Fixed application.yaml

k8s/mariadb-galera/schema.yaml
=> Fixed pattern and app name length

k8s/mariadb-galera/chart/mariadb-galera/templates/application.yaml
=> Deleted unneeded mariadb cluster service reference

triggers/k8s/zookeeper.yaml
**Category:**
---
Triger for zookeeper app
=> Triger for zookeeper

cloudbuild-triggers-check.yaml, scripts/triggers_check.sh
=> Add a new presubmit that verify trigger status.

cloudbuild-triggers-check.yaml
=> Check Docker triggers

triggers/triggers-check.yaml
=> Add trigger config for Triggers Check

scripts/triggers_check.sh
=> Use local variable

k8s/zookeeper/README.md
=> fix README.md by Dominik

vm/chef/cookbooks/mongodb/attributes/default.rb
=> Bump MongoDB to 4.2.0

k8s/zookeeper/README.md
=> fix on README.md by dkalgiewicz@

vm/chef/cookbooks/ceph/attributes/default.rb
=> Bumped ceph to nautilus

scripts/triggers_check.sh
=> Add more information to the output of the triggers check.

k8s/jenkins/Makefile
=> Upgrade Jenkins version in k8s app

k8s/jenkins/Makefile
=> Upgrade Jenkins version in k8s managed updates alpha to 2.190.1

k8s/mariadb-galera/README.md, k8s/mariadb-galera/chart/mariadb-galera/templates/application.yaml, k8s/mariadb-galera/schema.yaml
Tier 1 (quick/initial) Technical Writer review of MariaDB-Galera docs.
=> Tech Writer review - MariaDB-Galera - Tier 1

k8s/cassandra/Makefile, k8s/consul/Makefile, k8s/elastic-gke-logging/Makefile, k8s/elasticsearch/Makefile, k8s/etcd/Makefile, k8s/grafana/Makefile, k8s/influxdb/Makefile, k8s/jenkins/Makefile, k8s/mariadb-galera/Makefile, k8s/mariadb/Makefile, k8s/memcached/Makefile, k8s/nginx/Makefile, k8s/postgresql/Makefile, k8s/rabbitmq/Makefile, k8s/sonarqube/Makefile, k8s/wordpress/Makefile, k8s/zookeeper/Makefile
=> Update solutions Makefiles

vm/chef/cookbooks/odoo/attributes/default.rb, vm/chef/cookbooks/odoo/files/odoo-setup, vm/chef/cookbooks/odoo/metadata.rb, vm/chef/cookbooks/odoo/recipes/default.rb, vm/chef/cookbooks/odoo/templates/default/default-nginx.erb, vm/packer/templates/odoo/packer.in.json, vm/tests/solutions/spec/odoo/c2d_startup_spec.rb, vm/tests/solutions/spec/odoo/index_page_spec.rb, vm/tests/solutions/spec/odoo/ports_spec.rb, vm/tests/solutions/spec/odoo/services_spec.rb, vm/tests/solutions/spec/odoo/stackdriver_spec.rb, vm/tests/solutions/spec/odoo/users_spec.rb
The patch contains the Odoo VM application for GCP Click-to-deploy solution
=> Add Odoo vm application

k8s/consul/schema.yaml, k8s/etcd/schema.yaml, k8s/mariadb-galera/Makefile, k8s/mariadb-galera/schema.yaml
=> Add consul, etcd, mariadb-galera to kalm support

docker/README.md
=> Add magento and joomla

k8s/zookeeper/README.md, k8s/zookeeper/chart/zookeeper/templates/application.yaml, k8s/zookeeper/schema.yaml
Tier 1 (quick/initial) Technical Writer review of Zookeeper docs.
=> Tech Writer review - Zookeeper - Tier 1

triggers/k8s/magento.yaml
=> Add Magento 2 Trigger

k8s/zookeeper/README.md, k8s/zookeeper/chart/zookeeper/templates/application.yaml, k8s/zookeeper/schema.yaml
=> Tier 2 ZooKeeper edits

k8s/magento/chart/magento/templates/application.yaml
=> Fixed magento app documentation

k8s/joomla/README.md, k8s/joomla/chart/joomla/templates/application.yaml, k8s/joomla/schema.yaml
=> Joomla Tier 1 review edits

k8s/drupal/README.md
=> Drupal Tier 1 review edits

k8s/nuclio/chart/nuclio/templates/_helpers.tpl
=> Typo fix for Nuclio app

k8s/magento/README.md, k8s/magento/chart/magento/templates/application.yaml, k8s/magento/schema.yaml
=> Tier I Tech Writer edits - Magento

triggers/k8s/mediawiki.yaml
=> Add mediawiki trigger

triggers/k8s/activemq.yaml
=> add trigger for activemq

k8s/mediawiki/schema.yaml
=> Fix MediaWiki schema labels

k8s/mediawiki/chart/mediawiki/templates/application.yaml
=> Fix MediaWiki application.yaml

vm/chef/cookbooks/ceph/attributes/default.rb, vm/chef/cookbooks/elasticsearch/attributes/default.rb, vm/chef/cookbooks/elasticsearch/files/elasticsearch, vm/chef/cookbooks/elasticsearch/recipes/default.rb, vm/chef/cookbooks/mongodb/attributes/default.rb
=> Revert VM update

k8s/etcd/chart/etcd/templates/application.yaml, k8s/mariadb-galera/chart/mariadb-galera/templates/application.yaml
=> Fix types in application.yaml

k8s/mediawiki/chart/mediawiki/templates/application.yaml
=> Fix MediaWiki Ingress

k8s/consul/chart/consul/templates/application.yaml
=> Add (Managed Updates) title to Consul

k8s/memcached/Makefile, k8s/postgresql/Makefile, k8s/sonarqube/Makefile, k8s/zookeeper/Makefile, vm/chef/cookbooks/piwik/templates/default/install-piwik.json.erb
=> Add TODO comments. Fix a nit

k8s/activemq/schema.yaml, k8s/magento/schema.yaml, k8s/nuclio/schema.yaml, k8s/zookeeper/schema.yaml
=> add kalm/istio support to schema

k8s/jaeger-operator/README.md, k8s/jaeger-operator/chart/jaeger-operator/templates/application.yaml
=> Jaeger Operator - Tier I - Tech Writer review edits

k8s/prometheus-operator/README.md, k8s/prometheus-operator/chart/prometheus-operator/templates/application.yaml, k8s/prometheus-operator/schema.yaml
=> Prometheus Operator - Tier I - Tech Writer review edits

k8s/postgresql/Makefile
=> Updated PostgreSQL Makefile

k8s/activemq/README.md, k8s/activemq/schema.yaml
=> ActiveMQ - Tier I - Tech Writer review edits

k8s/grafana/Makefile
=> Update Grafana k8s app to 6.5 Track

k8s/activemq/README.md
=> fix storageclass confusion on Readme

k8s/mediawiki/README.md, k8s/mediawiki/chart/mediawiki/templates/application.yaml, k8s/mediawiki/schema.yaml
=> MediaWiki TW review - Tier I

k8s/prometheus/Makefile, k8s/prometheus/manifest/prometheus-configmap.yaml
=> updating prometheus Makefile

vm/chef/cookbooks/cassandra/attributes/default.rb, vm/chef/cookbooks/cassandra/files/cassandra
=> fixing chef scripts for cassandra v_3.11.5

triggers/k8s/hazelcast.yaml
=> Add Hazelcast Kubernetes Trigger

cloudbuild-vm.yaml, vm/chef/cookbooks/erpnext/attributes/default.rb, vm/chef/cookbooks/erpnext/files/erpnext-setup, vm/chef/cookbooks/erpnext/metadata.rb, vm/chef/cookbooks/erpnext/recipes/default.rb, vm/chef/cookbooks/erpnext/templates/default/etc-sudoers.d-frappeuser.erb, vm/packer/templates/erpnext/packer.in.json, vm/tests/config/erpnext, vm/tests/solutions/spec/erpnext/c2d_startup_spec.rb, vm/tests/solutions/spec/erpnext/index_page_spec.rb, vm/tests/solutions/spec/erpnext/ports_spec.rb, vm/tests/solutions/spec/erpnext/security_spec.rb, vm/tests/solutions/spec/erpnext/services_spec.rb, vm/tests/solutions/spec/erpnext/stackdriver_spec.rb, vm/tests/solutions/spec/erpnext/users_spec.rb
=> Added ERPNext VM solution

k8s/influxdb/README.md, k8s/influxdb/chart/influxdb/templates/influxdb-secrets.yaml, k8s/influxdb/schema.yaml
=> Fix base64 encoding for influxdb

k8s/cert-manager/Makefile, k8s/jaeger-operator/Makefile, k8s/nuclio/Makefile, k8s/prometheus-operator/Makefile
=> Removing unnecessary images from Makefiles

k8s/flink-operator/README.md, k8s/flink-operator/manifest/application.yaml, k8s/flink-operator/schema.yaml
=> Q1 Click to Deploy mass doc revamp, part 1

k8s/activemq/apptest/tester/Dockerfile
=> fix url for activemq binary on tester

k8s/activemq/README.md
=> Update README.md ActiveMQ

k8s/cert-manager/README.md, k8s/cert-manager/chart/cert-manager/templates/application.yaml, k8s/cert-manager/schema.yaml
=> TW review - Cert Manager - Tier I

k8s/hazelcast/README.md, k8s/hazelcast/chart/hazelcast/templates/application.yaml, k8s/hazelcast/schema.yaml
=> TW review - Hazelcast - Tier I

triggers/k8s/neo4j-ce.yaml
=> Add Neo4j trigger for Kubernetes Application

k8s/neo4j-ce/README.md
=> Fix Neo4j K8s README.md

vm/chef/cookbooks/sonarqube/attributes/default.rb, vm/chef/cookbooks/sonarqube/files/sonar-config-setup, vm/chef/cookbooks/sonarqube/metadata.rb, vm/chef/cookbooks/sonarqube/recipes/default.rb, vm/chef/cookbooks/sonarqube/templates/99-sonarqube.conf.erb, vm/chef/cookbooks/sonarqube/templates/sonar.conf.erb, vm/chef/cookbooks/sonarqube/templates/sonar.service.erb, vm/chef/cookbooks/sonarqube/templates/sysctl.conf.erb, vm/packer/templates/sonarqube/packer.in.json, vm/tests/solutions/spec/sonarqube/c2d_startup_spec.rb
=> adding VM sonarqube solution

k8s/jenkins/Makefile
=> Upgrade Jenkins k8s app from 2.190 to 2.222

.github/CODEOWNERS
=> Add Docker maintainers to CODEOWNERS

k8s/airflow-operator/README.md, k8s/cassandra/README.md, k8s/cert-manager/README.md, k8s/consul/README.md, k8s/flink-operator/README.md, k8s/jaeger-operator/README.md, k8s/nuclio/README.md, k8s/prometheus-operator/README.md, k8s/prometheus/README.md, k8s/rabbitmq/README.md, k8s/spark-operator/README.md
=> Include instructions to install envsubst in READMEs

docker/README.md
=> add orientdb-docker to the list

triggers/k8s/orientdb.yaml
=> add trigger for OrientDB k8s app

k8s/orientdb/Makefile
=> Update OrientDB to 3.0.x track

k8s/wordpress/chart/wordpress/templates/mysql-secrets.yaml, k8s/wordpress/chart/wordpress/templates/mysql-statefulset.yaml, k8s/wordpress/schema.yaml
=> K8s - Wordpress - Fix for schema and helm change

k8s/elasticsearch/README.md, k8s/elasticsearch/chart/elasticsearch/templates/manifests.yaml, k8s/elasticsearch/chart/elasticsearch/values.yaml, k8s/elasticsearch/schema.yaml
=> Add storageclass templating for Elasticsearch

k8s/rabbitmq/README.md, k8s/rabbitmq/chart/rabbitmq/templates/statefulset.yaml, k8s/rabbitmq/chart/rabbitmq/values.yaml, k8s/rabbitmq/schema.yaml
=> templating storageclass for RabbitMQ

k8s/elastic-gke-logging/README.md, k8s/elastic-gke-logging/chart/elastic-gke-logging/templates/elasticsearch-manifests.yaml, k8s/elastic-gke-logging/chart/elastic-gke-logging/values.yaml, k8s/elastic-gke-logging/schema.yaml
=> templating storageclass for elastic-gke-logging

k8s/cassandra/README.md, k8s/cassandra/chart/cassandra/templates/manifests.yaml, k8s/cassandra/chart/cassandra/values.yaml, k8s/cassandra/schema.yaml
=> add storageclass templating for Cassandra k8s app

triggers/k8s/gitlab.yaml
=> Added trigger for GitLab k8s app

k8s/magento/deployer/Dockerfile
=> Fixed Magento deployer timeout

k8s/nginx/README.md, k8s/nginx/chart/nginx/templates/nginx-config.yaml, k8s/nginx/chart/nginx/templates/nginx-secrets.yaml, k8s/nginx/chart/nginx/templates/nginx-services.yaml, k8s/nginx/chart/nginx/templates/nginx-statefulset.yaml, k8s/nginx/chart/nginx/values.yaml, k8s/nginx/schema.yaml
=> K8s NGINX - Add dynamic storageClass provisioning

vm/chef/cookbooks/php74/attributes/default.rb, vm/chef/cookbooks/php74/metadata.rb, vm/chef/cookbooks/php74/recipes/composer.rb, vm/chef/cookbooks/php74/recipes/default.rb, vm/chef/cookbooks/php74/recipes/module_cgi.rb, vm/chef/cookbooks/php74/recipes/module_cli.rb, vm/chef/cookbooks/php74/recipes/module_curl.rb, vm/chef/cookbooks/php74/recipes/module_gd.rb, vm/chef/cookbooks/php74/recipes/module_intl.rb, vm/chef/cookbooks/php74/recipes/module_json.rb, vm/chef/cookbooks/php74/recipes/module_libapache2.rb, vm/chef/cookbooks/php74/recipes/module_mbstring.rb, vm/chef/cookbooks/php74/recipes/module_mysql.rb, vm/chef/cookbooks/php74/recipes/module_opcache.rb, vm/chef/cookbooks/php74/recipes/module_readline.rb, vm/chef/cookbooks/php74/recipes/module_soap.rb, vm/chef/cookbooks/php74/recipes/module_xml.rb, vm/chef/cookbooks/php74/recipes/module_xmlrpc.rb, vm/chef/cookbooks/php74/recipes/module_xsl.rb, vm/chef/cookbooks/php74/recipes/module_zip.rb
=> Added PHP 7.4 chef cookbook

k8s/drupal/chart/drupal/templates/application.yaml, k8s/drupal/chart/drupal/templates/drupal-service.yaml, k8s/jenkins/chart/jenkins/templates/application.yaml, k8s/jenkins/chart/jenkins/templates/manifests.yaml, k8s/joomla/chart/joomla/templates/application.yaml, k8s/joomla/chart/joomla/templates/joomla-service.yaml, k8s/magento/chart/magento/templates/application.yaml, k8s/magento/chart/magento/templates/magento-ingress.yaml, k8s/mediawiki/chart/mediawiki/templates/application.yaml, k8s/mediawiki/chart/mediawiki/templates/mediawiki-ingress.yaml, k8s/wordpress/chart/wordpress/templates/application.yaml, k8s/wordpress/chart/wordpress/templates/wordpress-ingress.yaml
=> Change ingress api version to networking.k8s.io/v1beta1

k8s/jenkins/README.md, k8s/jenkins/chart/jenkins/templates/manifests.yaml, k8s/jenkins/chart/jenkins/values.yaml, k8s/jenkins/schema.yaml
=> template storageclass

k8s/grafana/README.md, k8s/grafana/chart/grafana/templates/statefulset.yaml, k8s/grafana/chart/grafana/values.yaml, k8s/grafana/schema.yaml
=> template storageclass for grafana

k8s/influxdb/README.md, k8s/influxdb/chart/influxdb/templates/manifests.yaml, k8s/influxdb/chart/influxdb/values.yaml, k8s/influxdb/schema.yaml
=> template storageclass for influxdb

k8s/mariadb-galera/README.md, k8s/mariadb-galera/chart/mariadb-galera/templates/statefulset.yaml, k8s/mariadb-galera/chart/mariadb-galera/values.yaml, k8s/mariadb-galera/schema.yaml
=> galera storageclass template

k8s/mediawiki/README.md, k8s/mediawiki/chart/mediawiki/templates/mariadb-statefulset.yaml, k8s/mediawiki/chart/mediawiki/templates/mediawiki-statefulset.yaml, k8s/mediawiki/chart/mediawiki/values.yaml, k8s/mediawiki/schema.yaml
=> template storageclass for mediawiki

vm/chef/cookbooks/kafka/attributes/default.rb
=> Update kafka 2.1.1 => 2.5.0

cloudbuild-docker.yaml
=> Set timeout for docker build

vm/chef/cookbooks/solr/attributes/default.rb
=> update solr 8.2 => 8.5

vm/chef/cookbooks/jenkins/attributes/default.rb
=> remove deployment-manager plugin

vm/chef/cookbooks/jenkins/attributes/default.rb
=> Update Jenkins plugins

k8s/grafana/README.md
=> K8s Grafana - Add service account reference to README

k8s/etcd/chart/etcd/templates/application.yaml
=> K8s - etcd - Fix Chart logo

vm/chef/cookbooks/solr/attributes/default.rb
=> VM - Solr - Upgrade version

vm/tests/solutions/spec/erpnext/index_page_spec.rb
=> VM - ERPNext - Fix index page test

vm/chef/cookbooks/elasticsearch/files/elasticsearch
=> VM - Elasticsearch 7 - Fix startup script for single-node deployment

docker/nuclio/CONTRIBUTING.md, docker/nuclio/LICENSE, docker/nuclio/README.md, docker/nuclio/nuclio_builder/Dockerfile, docker/nuclio/nuclio_builder/docker-entrypoint.sh, docker/nuclio/nuclio_builder/patch, docker/nuclio/nuclio_builder/scripts/controller, docker/nuclio/nuclio_builder/scripts/dashboard, docker/nuclio/templates/nuclio_builder/Dockerfile.template, docker/nuclio/versions.yaml
=> Added nuclio docker

cloudbuild-k8s.yaml
=> Add brackets to cloudbuild variables

docker/zookeeper/3/debian10/3.5/docker-entrypoint.sh, docker/zookeeper/3/debian10/3.6/docker-entrypoint.sh, docker/zookeeper/templates/debian10/docker-entrypoint.sh
=> fix entrypoint for servers

vm/chef/cookbooks/mariadb/attributes/default.rb, vm/chef/cookbooks/mariadb/files/mariadb-setup, vm/chef/cookbooks/mariadb/recipes/default.rb, vm/packer/templates/mariadb/packer.in.json, vm/tests/solutions/spec/mariadb/services_spec.rb
=> Rollback MariaDB to debian9 and test fix

vm/chef/cookbooks/mariadb/files/mariadb-setup
=> Typo fix for mariadb vm script

.github/workflows/label.yml
Fix actions/labeler when fork pull request occurs
https://github.com/actions/labeler/issues/12#issuecomment-670967607
/gcbrun
=> Change action trigger for label

docker/drupal/8/php7/debian9/8.9/apache/Dockerfile, docker/drupal/9/php7/debian9/9.0/apache/Dockerfile, docker/drupal/versions.yaml
=> [drupal] Docker images updates - 2020-10-08

docker/solr/versions.yaml
=> remove forgotten line

k8s/zookeeper/chart/zookeeper/templates/statefulset.yaml
=> change in ZK data dir

docker/solr/8/debian10/8.6/Dockerfile, docker/solr/templates/debian10/Dockerfile.template
=> added curl to package list

docker/drupal/8/php7/debian9/8.9/apache/Dockerfile, docker/drupal/versions.yaml
=> [drupal] Docker images updates - 2020-11-06

docker/jaeger-operator/1/1.20/Dockerfile, docker/jaeger-operator/CONTRIBUTING.md, docker/jaeger-operator/LICENSE, docker/jaeger-operator/README.md, docker/jaeger-operator/templates/Dockerfile.template, docker/jaeger-operator/versions.yaml
=> migrate jaeger-operator from gerrit

k8s/custom-governance/README.md, k8s/custom-governance/schema.yaml
Include some important dependencies in the prerequisites section in the readme.
=> Update Custom Governance's prerequisites part in README.md 

docker/drupal/8/php7/debian9/8.8/apache/Dockerfile, docker/drupal/8/php7/debian9/8.9/apache/Dockerfile, docker/drupal/9/php7/debian9/9.0/apache/Dockerfile, docker/drupal/versions.yaml
=> [drupal] Docker images updates - 2020-11-30

docker/drupal/8/php7/debian9/8.8/apache/docker-entrypoint.sh, docker/drupal/8/php7/debian9/8.9/apache/docker-entrypoint.sh, docker/drupal/9/php7/debian9/9.0/apache/docker-entrypoint.sh, docker/drupal/templates/docker-entrypoint.sh
=> Docker - Drupal - Await for MySQL be up before installing app

vm/packer/templates/kibana/packer.in.json
=> VM - Kibana - Fix license to be used in solution

vm/chef/cookbooks/cassandra/attributes/default.rb
=> VM - Cassandra - Fix latest patch from 3.11 version

docker/activemq/5/debian9/5.15/Dockerfile, docker/activemq/versions.yaml
=> [activemq] Docker images updates - 2020-12-11

k8s/elastic-gke-logging/chart/elastic-gke-logging/templates/kibana-manifests.yaml, k8s/elastic-gke-logging/deployer/Dockerfile
=> Increase liveness probe initial delay for kibana

k8s/cert-manager/schema.yaml, k8s/consul/schema.yaml, k8s/elastic-gke-logging/schema.yaml, k8s/gitlab/schema.yaml, k8s/grafana/schema.yaml, k8s/hazelcast/schema.yaml, k8s/jaeger-operator/schema.yaml, k8s/nuclio/schema.yaml, k8s/postgresql/schema.yaml, k8s/prometheus-operator/schema.yaml, k8s/prometheus/schema.yaml, k8s/rabbitmq/schema.yaml
=> K8s - Fixed Service Account missing descriptions

docker/activemq/5/debian9/5.16/Dockerfile, docker/activemq/versions.yaml
=> [activemq] Docker images updates - 2021-01-25

docker/drupal/8/php7/debian9/8.9/apache/Dockerfile, docker/drupal/9/php7/debian9/9.1/apache/Dockerfile, docker/drupal/versions.yaml
=> [drupal] Docker images updates - 2021-01-25

vm/tests/common/101_root_dir_checksum_test.sh
=> VM - Skip checking for gcloud and gsutil config folders

docker/drupal/9/php7/debian9/9.1/apache/Dockerfile, docker/drupal/versions.yaml
=> [drupal] Docker images updates - 2021-02-10

cloudbuild-docker.yaml, docker/gitlab/tests/functional_tests/health_test.yaml
=> Docker - Gitlab - Fix timeout for version 13.5

README.md
=> Updated worker-pools info in README

vm/chef/cookbooks/joomla/attributes/default.rb
=> VM - Joomla - Bump to 3.9.24

vm/tests/solutions/spec/piwik/ports_spec.rb
=> VM - Piwik/Matomo - Fix tests

vm/tests/solutions/spec/dokuwiki/ports_spec.rb
=> VM - DokuWiki - Fix tests

vm/chef/cookbooks/solr/attributes/default.rb, vm/chef/cookbooks/solr/recipes/default.rb
=> VM - Solr - Bump to 8.8.1

docker/drupal/9/php7/debian9/9.1/apache/Dockerfile, docker/drupal/versions.yaml
=> [drupal] Docker images updates - 2021-03-12

vm/chef/cookbooks/rabbitmq/attributes/default.rb, vm/chef/cookbooks/rabbitmq/files/rabbitmq, vm/chef/cookbooks/rabbitmq/recipes/default.rb, vm/packer/templates/rabbitmq/packer.in.json
=> VM - RabbitMQ - Upgrade to 3.8 track and fix clustering

vm/chef/cookbooks/erpnext/attributes/default.rb, vm/chef/cookbooks/erpnext/recipes/default.rb
=> VM - ERPNext - fixed mariadb package version attribute

docker/nuclio/versions.yaml
=> Docker - Nuclio - Fix tag

k8s/neo4j-ce/Makefile
=> K8s - Neo4j - Bump version to 4.1

k8s/orientdb/Makefile
=> K8s - OrientDB - Bump version to 3.1

k8s/memcached/Makefile
=> K8s - Memcached - Bump version to 1.6

k8s/rabbitmq/README.md
=> K8s - RabbitMQ - Add Helm 3 instructions

vm/chef/cookbooks/opencart/files/opencart-utils
=> VM - OpenCart - Fix nit

k8s/mediawiki/Makefile, k8s/mediawiki/apptest/tester/tests/exporters-suite.yaml, k8s/mediawiki/apptest/tester/tests/mediawiki-suite.yaml
=> K8s - MediaWiki - Bump version to 1.35.x

k8s/activemq/README.md, k8s/cert-manager/README.md, k8s/consul/README.md, k8s/drupal/README.md, k8s/elastic-gke-logging/README.md, k8s/etcd/README.md, k8s/grafana/README.md, k8s/hazelcast/README.md, k8s/jaeger-operator/README.md, k8s/jenkins/README.md, k8s/joomla/README.md, k8s/mariadb/README.md, k8s/memcached/README.md, k8s/neo4j-ce/README.md, k8s/nginx/README.md, k8s/postgresql/README.md, k8s/prometheus-operator/README.md, k8s/sonarqube/README.md, k8s/wordpress/README.md, k8s/zookeeper/README.md
Closed pull #929  and do the changes requested by @armandomiani here
Many Thank's
=> update helm examples to v3

k8s/prometheus/Makefile, k8s/prometheus/schema.yaml
=> K8s - Prometheus - Upgrade and fix sa roles

vm/chef/cookbooks/grafana/attributes/default.rb, vm/chef/cookbooks/grafana/recipes/default.rb
=> VM - Grafana - Rollback image to latest 7.4 version due licensing

docker/drupal/8/php7/debian9/8.9/apache/Dockerfile, docker/drupal/9/php7/debian9/9.1/apache/Dockerfile, docker/drupal/versions.yaml
=> [drupal] Docker images updates - 2021-05-11

docker/jaeger-operator/1/1.23/Dockerfile, docker/jaeger-operator/versions.yaml
=> Jaeger-operator - update to version 1.23.0

docker/drupal/9/php7/debian9/9.1/apache/Dockerfile, docker/drupal/9/php7/debian9/9.2/apache/Dockerfile, docker/drupal/9/php7/debian9/9.2/apache/docker-entrypoint.sh, docker/drupal/9/php7/debian9/9.2/apache/makedb.php, docker/drupal/versions.yaml
=> [drupal] Docker images updates - 2021-06-22

vm/chef/cookbooks/redmine/attributes/default.rb, vm/chef/cookbooks/redmine/files/redmine-startup, vm/chef/cookbooks/redmine/recipes/default.rb, vm/chef/cookbooks/redmine/templates/ruby-version.erb
=> VM - Redmine - Upgrade to 4.2.1

vm/chef/cookbooks/redash/attributes/default.rb, vm/chef/cookbooks/redash/recipes/default.rb
=> Redash - added missing dep package and removed comments

docker/activemq/README.md
=> Docker - ActiveMQ - Expanding README.md information

docker/mediawiki/README.md
=> Docker - Mediawiki - Expanding README.md information

docker/activemq/README.md
=> ActiveMQ readme fixes

docker/jaeger-operator/1/1.24/Dockerfile, docker/jaeger-operator/versions.yaml
=> Jaeger-operator - update to version 1.24.0

k8s/solr/Makefile, k8s/solr/apptest/tester/tests/solr-exporter-test.yaml, k8s/solr/apptest/tester/tests/solrCloud-test.yaml, k8s/solr/chart/solr/templates/exporter-deployment.yaml
=> K8s - Solr fix tests

vm/chef/cookbooks/nodenvm/README.md
=> VM - Add nodenvm cookbook doc

vm/chef/cookbooks/discourse/attributes/default.rb, vm/chef/cookbooks/discourse/files/discourse-setup, vm/chef/cookbooks/discourse/files/puma.service, vm/chef/cookbooks/discourse/metadata.rb, vm/chef/cookbooks/discourse/recipes/default.rb
Fix Ruby version and dependencies
Fix recipe and setup script
=> VM - Discourse - Fix application

docker/cert-manager/versions.yaml
=> [cert-manager] Docker images updates - 2021-08-09

docker/gitlab/14/debian9/14.1/Dockerfile, docker/gitlab/versions.yaml
=> [gitlab] Docker images updates - 2021-08-09

docker/cert-manager/1/debian9/1.4/Dockerfile, docker/cert-manager/versions.yaml
=> [cert-manager] Fix package version

docker/activemq/5/debian9/5.16/Dockerfile, docker/activemq/versions.yaml
=> [activemq] Docker images updates - 2021-08-19

scripts/triggers_check.sh
=> Triggers check - Fix parse when .triggers is not available

scripts/triggers_check.sh
=> Triggers check - Improve format checking

k8s/redis-ha/README.md, k8s/redis-ha/chart/redis-ha/templates/redis-statefulset.yaml, k8s/redis-ha/chart/redis-ha/values.yaml, k8s/redis-ha/schema.yaml
=> K8s - Redis - Add custom storage class

vm/chef/cookbooks/neo4j/attributes/default.rb, vm/chef/cookbooks/neo4j/recipes/default.rb
=> VM - neo4j - Chef 17 fix incompatibilities issues and upgrade to 4.3

vm/chef/cookbooks/grafana/attributes/default.rb, vm/chef/cookbooks/grafana/recipes/default.rb, vm/packer/templates/grafana/packer.in.json
=> Grafana - fix chef 17 compatibilities issues

vm/chef/cookbooks/discourse/recipes/default.rb, vm/chef/cookbooks/rvm/recipes/default.rb, vm/packer/templates/discourse/packer.in.json, vm/packer/templates/redmine/packer.in.json
=> Discourse | Redmine - gpg2 fix

vm/chef/cookbooks/cassandra/attributes/default.rb, vm/chef/cookbooks/cassandra/recipes/default.rb, vm/packer/templates/cassandra/packer.in.json
=> Cassandra - repo path fix & version update

docker/drupal/9/php7/debian9/9.2/apache/Dockerfile, docker/drupal/versions.yaml
=> [drupal] Docker images updates - 2021-11-05

k8s/joomla/Makefile
=> [joomla] k8s solution updates - 2021-11-05

vm/chef/cookbooks/sonarqube/files/sonar-config-setup
=> VM - Sonarqube - syntax fix

vm/chef/cookbooks/grafana/attributes/default.rb
=> VM - Grafana - version update

docker/README.md
=> Added haproxy to docker containers list

docker/prometheus-operator/0/0.34/Dockerfile, docker/prometheus-operator/CONTRIBUTING.md, docker/prometheus-operator/LICENSE, docker/prometheus-operator/README.md, docker/prometheus-operator/templates/Dockerfile.template, docker/prometheus-operator/versions.yaml
=> Docker - Migrate prometheus-operator from Gerrit

vm/chef/cookbooks/odoo/attributes/default.rb, vm/chef/cookbooks/odoo/recipes/default.rb
=> VM - Odoo - upgrade to version 15

vm/chef/cookbooks/erpnext/attributes/default.rb, vm/chef/cookbooks/erpnext/files/erpnext-setup, vm/chef/cookbooks/erpnext/recipes/default.rb
=> VM - Erpnext - startup fixes

vm/chef/cookbooks/redis/files/redis
=> VM - Redis - Fix Replication adding Authentication

vm/chef/cookbooks/jenkins/recipes/default.rb
=> VM - Jenkins - Fix for CVE-2021-44228

vm/chef/cookbooks/neo4j/files/neo4j
=> VM - Neo4J - Fix for CVE-2021-44228

vm/chef/cookbooks/sonarqube/attributes/default.rb, vm/chef/cookbooks/sonarqube/files/sonar-config-setup
=> VM - Sonarqube - fix for CVE-2021-44228

vm/chef/cookbooks/solr/attributes/default.rb, vm/chef/cookbooks/solr/templates/solr.erb
=> VM - Solr - fix for CVE-2021-44228

vm/chef/cookbooks/liferay/files/liferay-service
=> VM - Liferay - fix for CVE-2021-44228

k8s/neo4j-ce/chart/neo4j-ce/templates/neo4j-statefulset.yaml
=> K8s - Neo4j - Fix for CVE-2021-44228

k8s/jenkins/chart/jenkins/templates/jenkins-statefulset.yaml
=> K8s - Jenkins - Fix for CVE-2021-44228

k8s/rabbitmq/chart/rabbitmq/templates/statefulset.yaml
=> K8s - RabbitMQ - Fix for CVE-2021-44228

k8s/sonarqube/chart/sonarqube/templates/sonarqube-sts.yaml
=> K8s - Sonarqube - Fix for CVE-2021-44228

k8s/elasticsearch/chart/elasticsearch/templates/manifests.yaml
=> K8s - Elasticsearch - Fix for CVE-2021-44228

k8s/kafka/chart/kafka/templates/kafka-statefulset.yaml, k8s/kafka/chart/kafka/templates/zk-statefulset.yaml
=> K8s - Kafka - Fix for CVE-2021-44228

docker/neo4j/4/debian9/4.3/Dockerfile, docker/neo4j/templates/Dockerfile.template
=> Docker - Neo4j - Fix for CVE-2021-44228

docker/hazelcast/4/debian10/hazelcast-mc/4.2021/Dockerfile, docker/hazelcast/4/debian10/hazelcast/4.2/Dockerfile, docker/hazelcast/templates/hazelcast-mc4/Dockerfile.template, docker/hazelcast/templates/hazelcast4/Dockerfile.template
=> Docker - Hazelcast - Fix for CVE-2021-44228

docker/solr/8/debian10/8.10/Dockerfile, docker/solr/8/debian10/8.9/Dockerfile, docker/solr/templates/Dockerfile.template
=> Docker - Solr - Fix for CVE-2021-44228

vm/chef/cookbooks/magento/files/magento-config-redis, vm/chef/cookbooks/magento/files/magento-post-setup, vm/chef/cookbooks/magento/files/magento-setup, vm/chef/cookbooks/magento/metadata.rb, vm/chef/cookbooks/magento/recipes/default.rb, vm/tests/solutions/spec/magento/c2d_startup_spec.rb
=> VM - Magento - Fix setup and add Redis auth

vm/chef/cookbooks/wildfly/attributes/default.rb, vm/chef/cookbooks/wildfly/recipes/default.rb
=> VM - Wildfly - update to version 26.0.0

vm/chef/cookbooks/neo4j/attributes/default.rb
=> VM - Neo4j - update to version 4.4.2

vm/chef/cookbooks/jenkins/attributes/default.rb, vm/chef/cookbooks/jenkins/recipes/default.rb
=> VM - Jenkins - Do not install optional dependencies for groovy package

vm/chef/cookbooks/kafka/attributes/default.rb, vm/packer/templates/kafka/packer.in.json
=> VM - Kafka - update version to 3.0.0

docker/kafka/versions.yaml
=> Docker - Kafka - fix kafka3 container repo

vm/chef/cookbooks/moodle/attributes/default.rb, vm/packer/templates/moodle/packer.in.json
=> VM - Moodle - update to version 3.11.x

vm/chef/cookbooks/nodejs/recipes/default.rb, vm/packer/templates/nodejs/packer.in.json
=> VM - Node.js - upgrade to version 16.x

vm/chef/cookbooks/ruby/attributes/default.rb, vm/chef/cookbooks/ruby/recipes/default.rb, vm/packer/templates/rubystack/packer.in.json
=> VM - Ruby - upgrade to version 3.0.x

vm/chef/cookbooks/liferay/attributes/default.rb
=> VM - Liferay - upgrade to 7.4.3.8-ga8

vm/chef/cookbooks/wildfly/attributes/default.rb
=> VM - Wildfly - upgrade to 26.0.1

vm/chef/cookbooks/kafka/attributes/default.rb
=> VM - Kafka - upgrade to 3.1.0

vm/chef/cookbooks/tomcat/attributes/default.rb, vm/chef/cookbooks/tomcat/recipes/default.rb
=> VM - Tomcat - repo path fix and version update

vm/packer/templates/wordpress-ha/packer.in.json
=> VM - Wordpress-HA - update to Debian 10

vm/packer/templates/mysql8-book/packer.in.json
=> VM - Mysql8-book - update to Debian 10

vm/chef/cookbooks/solr/metadata.rb, vm/chef/cookbooks/solr/recipes/default.rb, vm/packer/templates/solr/packer.in.json
=> VM -Solr - update to Debian 10

vm/chef/cookbooks/sonarqube/attributes/default.rb
=> VM - Sonarqube - downgrade to 8.7.1 as per license restriction

vm/chef/cookbooks/resourcespace/attributes/default.rb
=> VM - Resourcespace - update to version 9.7

vm/chef/cookbooks/redmine/attributes/default.rb
=> VM - Redmine - update to version 4.2.3

vm/chef/cookbooks/redis/attributes/default.rb, vm/chef/cookbooks/redis/recipes/default.rb
=> VM - Redis - update to version 6.2.6

vm/chef/cookbooks/concretecms/attributes/default.rb, vm/chef/cookbooks/redis/files/sentinel.conf.template
=> VM - Redis - sentinel config fix

vm/chef/cookbooks/liferay/attributes/default.rb
=> VM - Liferay - updated to version 7.4.3.10-ga10

vm/chef/cookbooks/tomcat/attributes/default.rb, vm/chef/cookbooks/tomcat/recipes/default.rb
=> VM - Tomcat - Upgrade to 10.0.17

vm/chef/cookbooks/resourcespace/attributes/default.rb
=> VM - Resourcespace - Upgrade to 9.8

vm/chef/cookbooks/redmine/attributes/default.rb
=> VM - Redmine - Upgrade to 4.2.4

vm/chef/cookbooks/prestashop/attributes/default.rb
=> VM - Prestashop - Upgrade to 1.7.8.4

vm/chef/cookbooks/kubernetessandbox/attributes/default.rb
=> VM - Kubernetes Sandbox - Upgrade to 1.22.4

vm/chef/cookbooks/grafana/attributes/default.rb
=> VM - Grafana - Upgrade to 8.4.2

vm/chef/cookbooks/espocrm/attributes/default.rb
=> VM - EspoCRM - Upgrade to 7.0.9

vm/tests/solutions/spec/jenkins/ports_spec.rb
=> VM - Jenkins update to 2.332.1

vm/chef/cookbooks/pimcore/attributes/default.rb
=> VM - Pimcore - update to version 10.3.2

docker/knative/1/debian10/1.3/Dockerfile, docker/knative/CONTRIBUTING.md, docker/knative/LICENSE, docker/knative/README.md, docker/knative/templates/debian10/Dockerfile.template, docker/knative/versions.yaml
=> Docker - Knative - Docker dummy file

vm/chef/cookbooks/dolibarr/attributes/default.rb, vm/chef/cookbooks/dolibarr/recipes/default.rb
=> VM - Dolibarr - upgrade to version 15.0.1

vm/tests/solutions/spec/__common__/stackdriver_installed.rb, vm/tests/solutions/spec/memcached/ops_agent_spec.rb, vm/tests/solutions/spec/memcached/stackdriver_spec.rb
=>  VMs - Test fix for Stackdriver logging and ops-agent

vm/packer/templates/logstash/packer.in.json
=> VM - Logstash - Change license

k8s/hazelcast/Makefile
=> K8S - Hazelcast  - upgrade to verson 5.0.x

k8s/activemq/Makefile
=> [activemq] k8s solution updates - 2022-04-22

k8s/consul/Makefile
=> [consul] k8s solution updates - 2022-04-22

k8s/mediawiki/Makefile
=> K8S - Mediawiki - update to version 1.37 and PHP7.4

k8s/joomla/Makefile
=> K8S - Joomla - update to version 4.1 and PHP8

docker/knative/README.md
=> Docker - Knative- Improve README.md

vm/chef/cookbooks/couchdb/attributes/default.rb, vm/chef/cookbooks/couchdb/recipes/default.rb, vm/chef/cookbooks/piwik/attributes/default.rb
=> VM - CouchDB - build fix

k8s/hazelcast/apptest/deployer/schema.yaml, k8s/hazelcast/apptest/tester/tests/hazelcast-suite.yaml, k8s/hazelcast/schema.yaml
=> K8s - Hazelcast - Add permissions for deployer run the tests

k8s/jenkins/chart/jenkins/templates/jenkins-services.yaml
=> K8s - Jenkins - Support for 1.22

docker/activemq/5/debian10/5.17/Dockerfile, docker/activemq/versions.yaml
=> [activemq] Docker images updates - 2022-05-02

k8s/mariadb-galera/apptest/tester/tests/authentication-suite.yaml, k8s/redis-ha/chart/redis-ha/files/configs/haproxy.cfg
=> K8s - redis-ha - Remove the deprecated 'http-use-htx' option

k8s/mariadb-galera/apptest/tester/tests/authentication-suite.yaml, k8s/redis-ha/chart/redis-ha/files/configs/haproxy.cfg
=> K8s - mariadb galera - Update functional tests

docker/zookeeper/3/debian10/3.7/Dockerfile, docker/zookeeper/versions.yaml
=> [zookeeper] Docker images updates - 2022-05-16

docker/falco/versions.yaml
=> Docker - falco - Update versions.yaml

vm/chef/cookbooks/redis/attributes/default.rb
=> VM - Redis - upgrade to version 7.0.0

k8s/cassandra/apptest/tester/tests/basic-suite.yaml, k8s/cassandra/chart/cassandra/templates/cassandra-statefulset.yaml
=> K8S - Cassandra - tests fixes

docker/spark/3/debian11/3.3/Dockerfile, docker/spark/templates/3/Dockerfile.template, docker/spark/versions.yaml
=> Docker - Spark - Update source to stable releases

docker/superset/1/debian11/1.5/Dockerfile, docker/superset/exporter/Dockerfile, docker/superset/templates/Dockerfile.template, docker/superset/templates/exporter/Dockerfile.template, docker/superset/versions.yaml
=> Docker - Superset- added StatsD exporter

docker/superset/exporter/Dockerfile, docker/superset/templates/exporter/Dockerfile.template
=> Docker - Statsd-exporter - fixed binary file

vm/chef/cookbooks/concretecms/attributes/default.rb, vm/chef/cookbooks/concretecms/files/concretecms, vm/chef/cookbooks/concretecms/recipes/default.rb
=> VM - ConcreteCMS - installation fix

k8s/superset/chart/superset/templates/superset-service.yaml, k8s/superset/chart/superset/values.yaml
=> K8S - Superset - ingress port fix

vm/chef/cookbooks/dreamfactory/files/dreamfactory, vm/chef/cookbooks/dreamfactory/recipes/default.rb
=> VM -Dreamfactory - installation fix

vm/chef/cookbooks/weblate/files/weblate
=> Weblate - fixed libffi error during setup

vm/chef/cookbooks/wordpress/files/wordpress-multisite-setup, vm/chef/cookbooks/wordpress/files/wordpress-setup
=> VM - Wordpress - fixed cashing issue

docker/kafka/exporter/Dockerfile, docker/kafka/templates/exporter/Dockerfile.template
=> Docker - Kafka - Fix exporter openssl

docker/superset/1/debian11/1.5/Dockerfile, docker/superset/templates/Dockerfile.template
=> Docker - Superset - openssl fix

k8s/superset/README.md
=> K8S - Superset - README fixes

docker/superset/1/debian11/1.5/Dockerfile, docker/superset/templates/Dockerfile.template
=> Docker - Superset  - added Bigquery support

docker/drupal/9/php8/debian9/9.3/apache/Dockerfile, docker/drupal/9/php8/debian9/9.4/apache/Dockerfile, docker/drupal/versions.yaml
=> [drupal] Docker images updates - 2022-08-22

docker/gitlab/tests/functional_tests/health_test.yaml, docker/gitlab/versions.yaml
=> Docker - Change machineType for Gitlab solution

docker/storm/tests/functional_tests/running_test.yaml
=> Docker - Storm - test timeout increased

tools/cloudbuild-dockertools.yaml
=> Dockertools - Change artifacts location

tools/cloudbuild-dockertools.yaml
=> Dockertools - Fix secret version and target GCS

docker/activemq/5/debian11/5.17/Dockerfile, docker/activemq/README.md, docker/activemq/templates/Dockerfile.template
=> Docker - activemq - ./bin/activemq: ps: not found

docker/tikv/5/debian11/5.3/Dockerfile, docker/tikv/templates/Dockerfile.template
=> Docker - TiKV - Update unsecured packages

docker/conjur/1/debian11/1.18/Dockerfile, docker/conjur/templates/Dockerfile.template
```
Step #1: 2022/10/05 09:08:52 >>> Testing...
Step #1: 2022/10/05 09:08:52  > test-0 (Run test script)
Step #1: 2022/10/05 09:08:52 Running command (original): [docker exec some-conjur-$UNIQUE-id /usr/local/bin/run_test.sh]
Step #1: 2022/10/05 09:08:52 Running command (expanded): [docker exec some-conjur-0-0-id /usr/local/bin/run_test.sh]
Step #1: 2022/10/05 09:08:57 STDOUT>>Step 1. Create admin
Step #1: Admin key is 2ybcjcv21sc7gm2qc59qk20yt2a2322c3qv2sj97rb2887z7a2c2jhsq
Step #1: Step 2. Login with admin API key
Step #1: Auth token is eyJwcm90ZWN0ZWQiOiJleUpoYkdjaU9pSmpiMjVxZFhJdWIzSm5MM05zYjNOcGJHOHZkaklpTENKcmFXUWlPaUl3TVdJME9UQXpOREJqTVRnd05EYzFOVGd5WldVeU1qbGxNbVJqTmpkaE1XVTBabUV3WkdZNU9EazFNall4WlRFNU5qQmlOV1pqWTJVNE0yUXpNalk1SW4wPSIsInBheWxvYWQiOiJleUp6ZFdJaU9pSmhaRzFwYmlJc0ltVjR …
```
=> Docker - Conjur - Fix security issues

k8s/falco/Makefile
=> K8s - Falco - Upgrade to 0.32

docker/keycloak/19/debian11/19.0/Dockerfile, docker/keycloak/templates/Dockerfile.template, docker/keycloak/versions.yaml
```
Step #3: 2022/10/07 14:32:23 >>> Summary: PASSED
Step #3: 2022/10/07 14:32:23  > test-0 (Test health status): PASSED
```
=> Docker - Keycloak - Upgrade to 19.x and 18.0.2

docker/prometheus-operator/0/0.60/Dockerfile, docker/prometheus-operator/versions.yaml
=> Docker - prometheus-operator - update to version 0.60.1

docker/dragonfly/tests/functional_tests/dfget_test.yaml, docker/dragonfly/tests/functional_tests/scheduler_test.yaml, docker/dragonfly/tests/functional_tests/seed-peer_test.yaml
=> Docker - Dragonfly - Create solution.

docker/nuclio/1/debian11/nuclio-controller/1.10/Dockerfile, docker/nuclio/1/debian11/nuclio-dashboard/1.10/Dockerfile, docker/nuclio/templates/nuclio_controller/Dockerfile.template, docker/nuclio/templates/nuclio_dashboard/Dockerfile.template, docker/nuclio/versions.yaml
=> Docker - Nuclio - Fix security issues

docker/nuclio/1/debian11/nuclio-dashboard/1.10/Dockerfile, docker/nuclio/templates/nuclio_dashboard/Dockerfile.template
Docker - Nuclio - Update expat library
=> Docker - Nuclio - Update expat library

docker/nuclio/1/debian11/nuclio-dashboard/1.10/Dockerfile, docker/nuclio/templates/nuclio_dashboard/Dockerfile.template, docker/nuclio/versions.yaml
Docker - Nuclio - Update docker cli 19.03 -> 20.10.18
=> Docker - Nuclio - Update docker cli

vm/tests/common/200_solution_test.sh
=> VM - Fix net-ssh gem version

k8s/cassandra/scripts/restore.sh
```
Step #5 - "Verify Solution": DEPLOYER SMOKE_TEST I1202 10:55:40.867582       7 main.go:86] >>> Running /tests/basic-suite.yaml
Step #5 - "Verify Solution": DEPLOYER SMOKE_TEST I1202 10:55:40.880545       7 main.go:136]  >   0: There are exactly 3 nodes in a cluster
Step #5 - "Verify Solution": DEPLOYER SMOKE_TEST I1202 10:55:41.361176       7 main.go:141]  PASSED
Step #5 - "Verify Solution": DEPLOYER SMOKE_TEST I1202 10:55:41.361222       7 main.go:136]  >   1: Execute CQL query
Step #5 - "Verify Solution": DEPLOYER SMOKE_TEST I1202 10:55:51.517341       7 main.go:141]  PASSED
Step #5 - "Verify Solution": DEPLOYER SMOKE_TEST I1202 10:55:51.517584       7 main.go:136]  >   2: Cluster is connected
Step #5 - "Verify Solution": DEPLOYER SMOKE_TEST I1202 10:56:01.496544       7 …
```
=> K8S - Cassandra - Fix restore script

k8s/keycloak/Makefile, k8s/keycloak/README.md, k8s/keycloak/chart/keycloak/templates/webserver/keycloak-ingress.yaml, k8s/keycloak/chart/keycloak/templates/webserver/keycloak-tls.yaml, k8s/keycloak/chart/keycloak/values.yaml, k8s/keycloak/schema.yaml
```
Step #5 - "Verify Solution": DEPLOYER SMOKE_TEST + testrunner -logtostderr --test_spec=/tests/keycloak.yaml
Step #5 - "Verify Solution": DEPLOYER SMOKE_TEST I1129 10:23:44.240141       7 main.go:86] >>> Running /tests/keycloak.yaml
Step #5 - "Verify Solution": DEPLOYER SMOKE_TEST I1129 10:23:44.243511       7 main.go:136]  >   0: kubectl smoke test
Step #5 - "Verify Solution": DEPLOYER SMOKE_TEST I1129 10:23:44.363202       7 main.go:141]  PASSED
Step #5 - "Verify Solution": DEPLOYER SMOKE_TEST I1129 10:23:44.363414       7 main.go:136]  >   1: Wait for the webserver get ready
Step #5 - "Verify Solution": DEPLOYER SMOKE_TEST I1129 10:23:44.805273       7 main.go:141]  PASSED
Step #5 - "Verify Solution": DEPLOYER SMOKE_TEST I1129 10:23:44.805543       7 main.go:136]  >   2: Get master …
```
=> K8S - Keycloak - Fix ingress part

docker/gitea/1/debian11/1.16/Dockerfile, docker/gitea/templates/Dockerfile.template
=> Docker - Gitea - Update Dockerfile to have C2D env

.github/CODEOWNERS
=> CODEOWNERS - Move permissions to new group ccm-saap-team

docker/keycloak/18/debian11/18.0/Dockerfile, docker/keycloak/19/debian11/19.0/Dockerfile, docker/keycloak/20/debian11/20.0/Dockerfile, docker/keycloak/README.md, docker/keycloak/templates/Dockerfile.template, docker/keycloak/tests/functional_tests/running_test.yaml, docker/keycloak/versions.yaml
resolve security issues, add the latest release, update readme
```
Step #3 - "Test Solution": Step #3: 2022/12/26 13:56:31 >>> Testing...
Step #3 - "Test Solution": Step #3: 2022/12/26 13:56:31  > test-0 (Test health status)
Step #3 - "Test Solution": Step #3: 2022/12/26 13:56:31 Running command (original): [docker exec some-keycloak-$UNIQUE-id curl -s -L http://localhost:8080/realms/master]
Step #3 - "Test Solution": Step #3: 2022/12/26 13:56:31 Running command (expanded): [docker exec some-keycloak-0-0-id curl -s -L http://localhost:8080/realms/master]
Step #3 - "Test Solution": Step #3: 2022/12/26 13:56:32 STDOUT>>{"realm":"master","public_key":"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwQYxXVqzn1L+pumjT4QtU1Hyb7St3DjqEJ6YzegKHY8Nul9GO1K2s2PCypHgeunciVE6UVkrGrv2tnsfqQqAK/4gNB0QcSAvYkZ …
```
=> Docker - Keycloak - Update version

docker/crate/5/debian11/5.1/Dockerfile, docker/crate/versions.yaml
```
Step #3 - "Test Solution": Step #1: 2022/12/26 12:13:09 >>> Summary: PASSED
Step #3 - "Test Solution": Step #1: 2022/12/26 12:13:09  > test-0 (Create empty table): PASSED
Step #3 - "Test Solution": Step #1: 2022/12/26 12:13:09  > test-1 (Show tables): PASSED
Step #3 - "Test Solution": Finished Step #1
```
=> Docker - Crate - Update version

docker/dragonfly/2/debian11/2.0/dragonfly-dfget2/Dockerfile, docker/dragonfly/2/debian11/2.0/dragonfly-manager2/Dockerfile, docker/dragonfly/2/debian11/2.0/dragonfly-scheduler2/Dockerfile, docker/dragonfly/2/debian11/2.0/dragonfly-seed-peer2/Dockerfile, docker/dragonfly/versions.yaml
```
Step #3 - "Test Solution": Step #4: 2022/12/28 11:11:28 >>> Summary: PASSED
Step #3 - "Test Solution": Step #4: 2022/12/28 11:11:28  > test-0 (Test manager console page): PASSED
Step #3 - "Test Solution": Step #4: 2022/12/28 11:11:28  > test-1 (Manager health check): PASSED
Step #3 - "Test Solution": Finished Step #4
```
=> Docker - Dragonfly -Update version, use anchors

docker/django/4/debian11/4.1/Dockerfile, docker/django/templates/Dockerfile.template
=> Django - Fix Vulnerabilities

vm/chef/cookbooks/erpnext/attributes/default.rb, vm/chef/cookbooks/erpnext/recipes/default.rb, vm/chef/cookbooks/python/attributes/default.rb, vm/chef/cookbooks/python/metadata.rb, vm/chef/cookbooks/python/recipes/default.rb
=> VM - ERPNext - Upgrade to 14 and Python 3.10

docker/activemq/5/debian11/5.17/Dockerfile, docker/activemq/templates/Dockerfile.template, docker/activemq/versions.yaml
=> Docker- Activemq - Update version, fix vulnerabilities

docker/argo-workflows/3/debian11/3.4/Dockerfile, docker/argo-workflows/templates/Dockerfile.template, docker/argo-workflows/versions.yaml
=> Docker - Argo - Update version

k8s/cert-manager/Makefile
```
DEPLOYER SMOKE_TEST I0119 10:53:07.737086       7 main.go:86] >>> Running /tests/basic-suite.yaml
DEPLOYER SMOKE_TEST I0119 10:53:07.739471       7 main.go:136]  >   0: kubectl smoke test
DEPLOYER SMOKE_TEST I0119 10:53:07.827512       7 main.go:141]  PASSED
DEPLOYER SMOKE_TEST I0119 10:53:07.827557       7 main.go:136]  >   1: Wait for the webhook get ready
DEPLOYER SMOKE_TEST I0119 10:53:08.148311       7 main.go:141]  PASSED
DEPLOYER SMOKE_TEST I0119 10:53:08.148349       7 main.go:136]  >   2: Create test issuer and self signed cert
DEPLOYER SMOKE_TEST I0119 10:53:08.579490       7 main.go:141]  PASSED
DEPLOYER SMOKE_TEST I0119 10:53:08.579586       7 main.go:136]  >   3: Try to get new cert
DEPLOYER SMOKE_TEST I0119 10:53:09.440110       7 main.go:141]  PASSED
DEPLOYER SMOKE_TEST …
```
=> K8S - Cert-manager - Update version

docker/storm/versions.yaml
=> [storm] Docker images updates - 2023-01-20

docker/nuclio/1/debian11/nuclio-controller/1.11/Dockerfile, docker/nuclio/1/debian11/nuclio-dashboard/1.11/Dockerfile, docker/nuclio/versions.yaml
=> [nuclio] Docker images updates - 2023-01-20

k8s/falco/Makefile
```
DEPLOYER SMOKE_TEST I0120 12:21:40.104836       7 main.go:86] >>> Running /tests/basic-suite.yaml
DEPLOYER SMOKE_TEST I0120 12:21:40.107426       7 main.go:136]  >   0: Are there all Falco pods healthy
DEPLOYER SMOKE_TEST I0120 12:21:41.108269       7 main.go:141]  PASSED
DEPLOYER SMOKE_TEST I0120 12:21:41.108318       7 main.go:136]  >   1: Is Falco /metrics HTTP endpoint working for Prometheus metrics
DEPLOYER SMOKE_TEST I0120 12:22:01.131146       7 main.go:141]  PASSED
DEPLOYER SMOKE_TEST I0120 12:22:01.131261       7 main.go:117]  >> Summary: PASSED
DEPLOYER SMOKE_TEST I0120 12:22:01.131270       7 main.go:123]  >   0: Are there all Falco pods healthy: PASSED
DEPLOYER SMOKE_TEST I0120 12:22:01.131274       7 main.go:123]  >   1: Is Falco /metrics HTTP endpoint working for …
```
=> K8S - falco - Update version

docker/django/4/debian11/4.1/Dockerfile, docker/django/versions.yaml
=> [django] Docker images updates - 2023-01-23-114627

docker/gitea/1/debian11/1.18/Dockerfile, docker/gitea/templates/Dockerfile.template, docker/gitea/versions.yaml
=> Docker- Gitea - Update version

docker/mediawiki/1/debian11/1.39/Dockerfile, docker/mediawiki/templates/Dockerfile.template
=> Docker - Mediawiki - Fix curl

k8s/nginx/Makefile
=> K8S - Nginx - update image

k8s/nuclio/Makefile
```
I0207 11:18:15.631938       7 main.go:86] >>> Running /tests/basic-suite.yaml
I0207 11:18:15.632994       7 main.go:136]  >   0: Nuctl smoke test
I0207 11:18:15.670822       7 main.go:141]  PASSED
I0207 11:18:15.670850       7 main.go:136]  >   1: Test nuclio deploy
I0207 11:20:14.243979       7 main.go:141]  PASSED
I0207 11:20:14.244025       7 main.go:136]  >   2: Try to get IP of nuclio service
I0207 11:20:14.290083       7 main.go:141]  PASSED
I0207 11:20:14.290259       7 main.go:136]  >   3: Try to connect to nuclio service
I0207 11:20:23.504779       7 main.go:141]  PASSED
I0207 11:20:23.504987       7 main.go:136]  >   4: Try to use nuclio service
I0207 11:20:23.548850       7 main.go:141]  PASSED
I0207 11:20:23.548889       7 main.go:136]  >   5: Delete test nuclio deploy …
```
=> K8S - Nuclio - update version

docker/airflow/README.md
=> Docker - Airflow - Update README.md

docker/c2d-debian/11/debian11/Dockerfile, docker/c2d-debian/README.md, docker/c2d-debian/templates/Dockerfile.template, docker/c2d-debian/versions.yaml
=> Docker - C2D Debian 11 - add image

docker/conjur/1/debian11/1.19/Dockerfile, docker/conjur/templates/Dockerfile.template, docker/conjur/versions.yaml
=> Docker - Conjur - Change baseimage, update version

docker/crate/5/debian11/5.2/Dockerfile, docker/crate/templates/Dockerfile.template, docker/crate/versions.yaml
=> Docker - Crate - Change baseimage, update version

docker/gogs/0/debian11/0.12/Dockerfile, docker/gogs/templates/Dockerfile.template, docker/gogs/versions.yaml
=> Docker - Gogs - Change baseimage

docker/harbor/2/debian11/2.7/Dockerfile, docker/harbor/versions.yaml
=> Docker - Harbor - update baseimage

docker/gitea/1/debian11/1.18/Dockerfile, docker/gitea/templates/Dockerfile.template, docker/gitea/versions.yaml
=> Docker - Gitea - update baseimage

k8s/harbor/Makefile
=> K8S - Harbor - update version

docker/hydra/2/debian11/2.0/Dockerfile, docker/hydra/templates/Dockerfile.template, docker/hydra/versions.yaml
=> Docker - Hydra - Update baseimage.

docker/activemq/5/debian11/5.17/Dockerfile, docker/activemq/templates/Dockerfile.template, docker/activemq/versions.yaml, docker/airflow/2/debian11/2.5/Dockerfile, docker/airflow/versions.yaml, docker/argo-workflows/3/debian11/3.4/Dockerfile, docker/argo-workflows/templates/Dockerfile.template, docker/argo-workflows/versions.yaml
=> Docker - Activemq, Airflow, Argo - update version

docker/superset/1/debian11/1.5/Dockerfile, docker/superset/exporter/Dockerfile, docker/superset/templates/Dockerfile.template, docker/superset/versions.yaml
=> Docker - Superset - Upgrade to 1.5.3 and use c2d-debian11

docker/cert-manager/1/debian11/1.11/Dockerfile, docker/cert-manager/templates/cert-manager1/Dockerfile.template, docker/cert-manager/versions.yaml, docker/django/4/debian11/4.1/Dockerfile, docker/django/exporter/Dockerfile, docker/django/templates/exporter/Dockerfile.template, docker/django/versions.yaml
=> Docker - Cert-manager, Django - update baseimages

docker/prometheus-operator/0/0.63/Dockerfile, docker/prometheus-operator/versions.yaml
=> Docker - prometheus-operator - Upgrade to 0.63

docker/keycloak/18/debian11/18.0/Dockerfile, docker/keycloak/19/debian11/19.0/Dockerfile, docker/keycloak/20/debian11/20.0/Dockerfile, docker/keycloak/versions.yaml
=> [keycloak] Docker images updates - 2023-02-21-115602

docker/harbor/2/debian11/2.7/Dockerfile, docker/harbor/versions.yaml
=> [harbor] Docker images updates - 2023-02-21-120846

docker/c2d-debian/11/debian11/Dockerfile, docker/c2d-debian/templates/Dockerfile.template
=> Docker - Debian - Fix openssl issue

k8s/hazelcast/Makefile, k8s/hazelcast/chart/hazelcast/templates/hazelcast-statefulset.yaml
=> [hazelcast] k8s solution updates - 2023-02-27

k8s/joomla/Makefile
=> [joomla] k8s solution updates - 2023-02-27

docker/jaeger-operator/1/debian11/1.40/Dockerfile, docker/jaeger-operator/versions.yaml
=> Docker - Jaeger-Operator - Update baseimage to c2d-debian11

docker/knative/1/debian11/1.3/Dockerfile, docker/knative/1/debian11/1.9/Dockerfile, docker/knative/versions.yaml
=> Docker - Knative - Update version

docker/prometheus-operator/0/0.63/Dockerfile, docker/prometheus-operator/templates/Dockerfile.template
=> Docker - prometheus-operator - Fix hardcoded image

docker/nuclio/1/debian11/nuclio-controller/1.11/Dockerfile, docker/nuclio/1/debian11/nuclio-dashboard/1.11/Dockerfile, docker/nuclio/templates/nuclio_controller/Dockerfile.template, docker/nuclio/templates/nuclio_dashboard/Dockerfile.template
=> Docker - Nuclio - Cleanup templates

docker/gitea/versions.yaml
=> [gitea] Docker images updates - 2023-03-02-131227

docker/activemq/5/debian11/5.17/Dockerfile, docker/activemq/templates/Dockerfile.template, docker/activemq/versions.yaml
=> [activemq] Docker images updates - 2023-03-02-144538

vm/chef/cookbooks/mariadb/attributes/default.rb, vm/packer/templates/mariadb/packer.in.json, vm/tests/solutions/spec/mariadb/ops_agent_spec.rb, vm/tests/solutions/spec/mariadb/stackdriver_spec.rb, vm/tests/solutions/spec/mariadb/version_spec.rb
=> VM - MariaDB - Upgrade to 10.11  and Debian 11

docker/airflow/2/debian11/2.5/Dockerfile, docker/airflow/versions.yaml
=> [airflow] Docker images updates - 2023-03-03-102834

docker/c2d-debian/11/debian11/Dockerfile, docker/c2d-debian/templates/Dockerfile.template
=> Docker - C2D-Debian - Fix libaprutil1

k8s/hazelcast/Makefile, k8s/hazelcast/chart/hazelcast/templates/hazelcast-statefulset.yaml
=> K8s - Hazelcast - Update mancenter track 

docker/dragonfly/2/debian11/2.0/dragonfly-dfget2/Dockerfile, docker/dragonfly/2/debian11/2.0/dragonfly-manager2/Dockerfile, docker/dragonfly/2/debian11/2.0/dragonfly-scheduler2/Dockerfile, docker/dragonfly/2/debian11/2.0/dragonfly-seed-peer2/Dockerfile, docker/dragonfly/versions.yaml
=> Docker - Dragonfly - Update baseimage

vm/chef/cookbooks/moodle/attributes/default.rb, vm/chef/cookbooks/moodle/files/moodle, vm/chef/cookbooks/moodle/metadata.rb, vm/chef/cookbooks/moodle/recipes/default.rb, vm/packer/templates/moodle/packer.in.json, vm/tests/solutions/spec/moodle/c2d_startup_spec.rb, vm/tests/solutions/spec/moodle/ops_agent_spec.rb, vm/tests/solutions/spec/moodle/php_config_spec.rb, vm/tests/solutions/spec/moodle/stackdriver_spec.rb
=> VM - Moodle - Update to 4.4.1, PHP 8.1, MySQL 8 and Debian 11

vm/chef/cookbooks/ghost/attributes/default.rb, vm/chef/cookbooks/ghost/files/ghost, vm/chef/cookbooks/ghost/recipes/default.rb, vm/packer/templates/ghost/packer.in.json, vm/tests/solutions/spec/ghost/c2d_startup_spec.rb, vm/tests/solutions/spec/ghost/ops_agent_spec.rb, vm/tests/solutions/spec/ghost/stackdriver_spec.rb, vm/tests/solutions/spec/moodle/ops_agent_spec.rb
=> VM - Ghost - Update to 5.37.0, MySQL 8 and Debian 11

vm/chef/cookbooks/redash/recipes/default.rb
=> VM - Redash - Add docker-composer file, not included since version 9.x

vm/chef/cookbooks/wordpress/templates/wordpress-http.conf.erb, vm/chef/cookbooks/wordpress/templates/wordpress-https.conf.erb
http://vulnstore/#advisories&expand=true&q=publisher:QUALYS+reference:12882
=> VM - WordPress - Disable xmlrpc feature

vm/chef/cookbooks/opencart/attributes/default.rb, vm/chef/cookbooks/opencart/files/opencart, vm/chef/cookbooks/opencart/files/opencart-utils, vm/chef/cookbooks/opencart/metadata.rb, vm/chef/cookbooks/opencart/recipes/default.rb, vm/packer/templates/opencart/packer.in.json, vm/tests/solutions/spec/opencart/c2d_startup_spec.rb, vm/tests/solutions/spec/opencart/ops_agent_spec.rb, vm/tests/solutions/spec/opencart/php_config_spec.rb, vm/tests/solutions/spec/opencart/stackdriver_spec.rb
=> VM - OpenCart - Update to PHP 8 , Debian 11 and MySQL 8

docker/neo4j/5/debian11/5.5/docker-entrypoint.sh, docker/neo4j/templates/neo4j5/docker-entrypoint.sh
=> Docker - Neo4j - Fix entrypoint

docker/tikv/versions.yaml
=> Docker - Tikv - Fix repo name

vm/chef/cookbooks/joomla/attributes/default.rb, vm/chef/cookbooks/joomla/metadata.rb, vm/chef/cookbooks/joomla/recipes/default.rb, vm/tests/solutions/spec/joomla/php_config_spec.rb
=> VM - Joomla - Upgrade to 4.2.9 and PHP 8.1

docker/hazelcast/5/debian11/hazelcast-mc/5.2/Dockerfile, docker/hazelcast/templates/hazelcast-mc5/Dockerfile.template, docker/hazelcast/versions.yaml
=> Docker - Hazelcast - Remove MC sha256

docker/solr/9/debian11/9.1/Dockerfile, docker/solr/templates/Dockerfile.template, docker/solr/versions.yaml
=> Docker - Solr - Remove sha checks

vm/chef/cookbooks/ruby/attributes/default.rb, vm/chef/cookbooks/ruby/recipes/default.rb
=> VM - Ruby - Upgrade to 3.2.1

vm/chef/cookbooks/tomcat/attributes/default.rb, vm/packer/templates/tomcat/packer.in.json
=> VM - Tomcat - Upgrade to 10.1.7

docker/activemq/5/debian11/5.18/Dockerfile, docker/activemq/5/debian11/5.18/docker-entrypoint.sh, docker/activemq/versions.yaml
=> [activemq] Docker images updates - 2023-03-31-085214

docker/airflow/2/debian11/2.5/Dockerfile, docker/airflow/versions.yaml
=> [airflow] Docker images updates - 2023-03-31-085220

docker/falco/0/debian11/0.33/Dockerfile, docker/falco/0/debian11/0.33/docker-entrypoint.sh, docker/falco/versions.yaml
=> [falco] Docker images updates - 2023-03-31-085406

docker/airflow/2/debian11/2.5/Dockerfile, docker/airflow/versions.yaml
=> [airflow] Docker images updates - 2023-04-05-103745

docker/argo-workflows/3/debian11/3.4/Dockerfile, docker/argo-workflows/versions.yaml
=> [argo-workflows] Docker images updates - 2023-04-05-103759

docker/crate/5/debian11/5.3/Dockerfile, docker/crate/5/debian11/5.3/config/crate.yml, docker/crate/5/debian11/5.3/config/log4j2.properties, docker/crate/5/debian11/5.3/docker-entrypoint.sh, docker/crate/versions.yaml
=> [crate] Docker images updates - 2023-04-05-103835

docker/django/4/debian11/4.1/Dockerfile, docker/django/versions.yaml
=> [django] Docker images updates - 2023-04-05-103847

docker/keycloak/21/debian11/21.0/Dockerfile, docker/keycloak/versions.yaml
=> [keycloak] Docker images updates - 2023-04-05-104054

vm/chef/cookbooks/zabbix/recipes/default.rb
=> VM - Zabbix - Fix Zabbix configuration paths

vm/chef/cookbooks/limesurvey/attributes/default.rb, vm/chef/cookbooks/limesurvey/files/limesurvey-utils, vm/chef/cookbooks/limesurvey/recipes/default.rb, vm/tests/solutions/spec/limesurvey/c2d_startup_spec.rb
=> VM - LimeSurvey - Upgrade to 5.6 and fix mysql 8 user setup

vm/chef/cookbooks/mysql/files/mysql8-root-localhost-password-setup, vm/chef/cookbooks/mysql/recipes/install-and-configure-mysqld8.rb, vm/chef/cookbooks/mysql/recipes/version-8.0.rb, vm/chef/cookbooks/pimcore/attributes/default.rb
=> VM - PimCore - Upgrade to 10.5.20

vm/chef/cookbooks/pimcore/files/apache-pimcore-website.htaccess, vm/chef/cookbooks/pimcore/files/pimcore, vm/chef/cookbooks/pimcore/recipes/default.rb
=> VM - Pimcore - Fix apache configuration

k8s/hydra/chart/hydra/templates/application.yaml, k8s/hydra/chart/hydra/templates/hpa.yaml
=> K8S - Hydra - Fix deprecated apis

vm/chef/cookbooks/liferay/attributes/default.rb, vm/chef/cookbooks/liferay/files/liferay-db-setup, vm/chef/cookbooks/liferay/recipes/default.rb, vm/packer/templates/liferay/packer.in.json, vm/tests/config/liferay, vm/tests/solutions/spec/liferay/c2d_startup_spec.rb, vm/tests/solutions/spec/liferay/ops_agent_spec.rb, vm/tests/solutions/spec/liferay/stackdriver_spec.rb
=> VM - Liferay - Upgrade to 7.4.3.72 and Debian 11

docker/argo-workflows/3/debian11/3.4/Dockerfile, docker/argo-workflows/versions.yaml
=> [argo-workflows] Docker images updates - 2023-04-21-125854

docker/gitlab/15/debian11/15.10/Dockerfile, docker/gitlab/versions.yaml
=> [gitlab] Docker images updates - 2023-04-21-130217

docker/activemq/5/debian11/5.18/Dockerfile, docker/activemq/versions.yaml
=> [activemq] Docker images updates - 2023-04-21-125824

docker/drupal/10/php8/debian11/10.0/apache/Dockerfile, docker/drupal/9/php8/debian11/9.5/apache/Dockerfile, docker/drupal/versions.yaml
=> [drupal] Docker images updates - 2023-04-21-130014

docker/harbor/2/debian11/2.8/Dockerfile, docker/harbor/versions.yaml
=> [harbor] Docker images updates - 2023-04-21-130327

docker/hydra/2/debian11/2.1/Dockerfile, docker/hydra/versions.yaml
=> [hydra] Docker images updates - 2023-04-21-130339

docker/conjur/1/debian11/1.19/Dockerfile, docker/conjur/versions.yaml
=> [conjur] Docker images updates - 2023-04-21-125951

docker/nuclio/1/debian11/nuclio-controller/1.11/Dockerfile, docker/nuclio/1/debian11/nuclio-dashboard/1.11/Dockerfile, docker/nuclio/versions.yaml
=> [nuclio] Docker images updates - 2023-04-21-130801

docker/gitea/versions.yaml
=> [gitea] Docker images updates - 2023-04-21-130201

k8s/cassandra/apptest/tester/Dockerfile, k8s/dragonfly/apptest/tester/Dockerfile, k8s/drupal/apptest/tester/Dockerfile, k8s/joomla/apptest/tester/Dockerfile, k8s/magento/apptest/tester/Dockerfile, k8s/mariadb-galera/apptest/tester/Dockerfile, k8s/mariadb/apptest/tester/Dockerfile, k8s/mediawiki/apptest/tester/Dockerfile, k8s/wordpress/apptest/tester/Dockerfile
=> K8S - Cassandra Dragonfly Drupal Joomla Magento Mariadb Mediawiki Wordpress  -fix python and mysql-client packages

k8s/neo4j-ce/apptest/tester/Dockerfile, k8s/postgresql/apptest/tester/Dockerfile, k8s/zookeeper/apptest/tester/Dockerfile
=> K8S - Neo4j Postgresql Zookeeper - Fix tests

k8s/falco/apptest/tester/tests/basic-suite.yaml, k8s/kafka/apptest/tester/Dockerfile
=> K8S - Falco Kafka - Fix tests

k8s/airflow/README.md, k8s/airflow/schema.yaml
https://b.corp.google.com/issues/250711554
Daniel Hipke: Probably we should update it to read "Persistent Volumes".
=> K8S - Airflow - Rename pvs

docker/crate/5/debian11/5.2/Dockerfile, docker/crate/5/debian11/5.3/Dockerfile, docker/crate/versions.yaml
=> [crate] Docker images updates - 2023-05-10-103027

docker/django/4/debian11/4.2/Dockerfile, docker/django/4/debian11/4.2/docker-entrypoint.sh, docker/django/versions.yaml
=> [django] Docker images updates - 2023-05-10-103031

docker/drupal/10/php8/debian11/10.0/apache/Dockerfile, docker/drupal/9/php8/debian11/9.5/apache/Dockerfile, docker/drupal/versions.yaml
=> [drupal] Docker images updates - 2023-05-10-103037

docker/harbor/2/debian11/2.7/Dockerfile, docker/harbor/versions.yaml
=> [harbor] Docker images updates - 2023-05-10-103145

docker/airflow/2/debian11/2.6/Dockerfile, docker/airflow/2/debian11/2.6/scripts/docker/install_airflow.sh, docker/airflow/2/debian11/2.6/scripts/docker/install_mssql.sh, docker/airflow/2/debian11/2.6/scripts/docker/install_mysql.sh, docker/airflow/2/debian11/2.6/scripts/docker/install_pip_version.sh, docker/airflow/2/debian11/2.6/scripts/prod/clean-logs.sh, docker/airflow/2/debian11/2.6/scripts/prod/entrypoint_prod.sh, docker/airflow/versions.yaml
=> [airflow] Docker images updates - 2023-05-10-102946

docker/gitlab/15/debian11/15.11/Dockerfile, docker/gitlab/versions.yaml
=> [gitlab] Docker images updates - 2023-05-18-105531

docker/longhorn/1/debian11/1.4/Dockerfile, docker/longhorn/versions.yaml
=> [longhorn] Docker images updates - 2023-05-18-105801

docker/airflow/2/debian11/2.6/Dockerfile, docker/airflow/versions.yaml
=> [airflow] Docker images updates - 2023-05-18-105350

docker/nuclio/1/debian11/nuclio-controller/1.11/Dockerfile, docker/nuclio/1/debian11/nuclio-dashboard/1.11/Dockerfile, docker/nuclio/versions.yaml
=> Docker - Nuclio - Upgrade 1.11.16 -> 1.11.20

scripts/download-licenses.sh, scripts/download-ref-repos.sh, scripts/download-repos.sh, scripts/trigger-solution-tests.sh
Scripts will be used by Containers and VMs in order to download licenses and source-code into image for compliance-purpose
=> Add scripts for open-source licensing automation

docker/airflow/2/debian11/2.5/Dockerfile, docker/airflow/2/debian11/2.6/Dockerfile, docker/airflow/templates/Dockerfile.template, docker/airflow/versions.yaml
=> Docker - Airflow - Upgrade to 2.6.3 and fix build

docker/activemq/5/debian11/5.18/Dockerfile, docker/activemq/versions.yaml
=> [activemq] Docker images updates - 2023-08-16-225514

docker/airflow/2/debian11/2.7/Dockerfile, docker/airflow/2/debian11/2.7/scripts/docker/install_airflow.sh, docker/airflow/2/debian11/2.7/scripts/docker/install_mssql.sh, docker/airflow/2/debian11/2.7/scripts/docker/install_mysql.sh, docker/airflow/2/debian11/2.7/scripts/docker/install_pip_version.sh, docker/airflow/2/debian11/2.7/scripts/prod/clean-logs.sh, docker/airflow/2/debian11/2.7/scripts/prod/entrypoint_prod.sh, docker/airflow/versions.yaml
=> [airflow] Docker images updates - 2023-09-14-123814

docker/gitlab/16/debian11/16.3/Dockerfile, docker/gitlab/versions.yaml
=> Docker - Gitlab -  updated version to 16.3.4

docker/hydra/tests/functional_tests/functional_test.yaml
=> Docker - Hydra - Fix PostgreSQL container path

docker/cert-manager/1/debian11/1.13/Dockerfile, docker/cert-manager/versions.yaml
=> Docker - Cert-Manager - Upgrade to 1.13.1

docker/gitlab/tests/functional_tests/health_test.yaml
=> Docker - Gitlab - Increased time for functional_tests

vm/chef/cookbooks/cassandra/attributes/default.rb
=> VM - Cassandra - Upgrade to 4.1.3

vm/chef/cookbooks/erpnext/attributes/default.rb, vm/chef/cookbooks/erpnext/metadata.rb, vm/chef/cookbooks/erpnext/recipes/default.rb, vm/tests/solutions/spec/dreamfactory/c2d_startup_spec.rb, vm/tests/solutions/spec/erpnext/c2d_startup_spec.rb, vm/tests/solutions/spec/erpnext/ports_spec.rb, vm/tests/solutions/spec/erpnext/services_spec.rb
=> VM - ERPNext - Fix tests and reuse Redis cookbook

vm/chef/cookbooks/phpmyadmin/attributes/default.rb
=> VM - phpmyadmin - Bump phpmyadmin to 5.2.1

docker/harbor/2/debian11/2.7/Dockerfile, docker/harbor/2/debian11/2.9/Dockerfile, docker/harbor/versions.yaml
=> [harbor] Docker images updates - 2023-12-15-104114

docker/activemq/5/debian11/5.18/Dockerfile, docker/activemq/versions.yaml
=> Docker -  Activemq updated to version 5.18.3

docker/activemq/5/debian11/5.18/Dockerfile, docker/activemq/templates/Dockerfile.template
=> Docker - Activemq - openjdk updated to 17

vm/chef/cookbooks/kafka/attributes/default.rb
=> VM - Kafka version updated to 3.6.1/ scala updated to 2.13

vm/chef/cookbooks/pimcore/attributes/default.rb
=> VM - Pimcore version updated to 11.1.4

vm/chef/cookbooks/ghost/attributes/default.rb, vm/chef/cookbooks/ghost/recipes/default.rb
=> VM - Ghost version updated to 1.25.3/ nodejs updated to version 19

vm/chef/cookbooks/zabbix/attributes/default.rb
=> VM - Zabbix version updated to 6.5

vm/chef/cookbooks/mautic/attributes/default.rb
=> VM - Mautic version updated to 4.4.10

vm/chef/cookbooks/erpnext/attributes/default.rb
=> VM - Erpnext version updated to 15 and nodejs updated to version 19

docker/cert-manager/1/debian11/1.11/Dockerfile, docker/cert-manager/1/debian11/1.13/Dockerfile, docker/cert-manager/templates/cert-manager1/Dockerfile.template, docker/cert-manager/versions.yaml
=> Docker - cert-manager version updated to 1.13.3 and ca-certficate added

docker/crate/5/debian11/5.3/Dockerfile, docker/crate/5/debian11/5.5/Dockerfile, docker/crate/versions.yaml
=> [crate] Docker images updates - 2024-01-18-101252

docker/harbor/2/debian11/2.10/Dockerfile, docker/harbor/versions.yaml
=> [harbor] Docker images updates - 2024-01-18-101353

docker/jaeger-operator/versions.yaml
=> [jaeger-operator] Docker images updates - 2024-01-18-101412

docker/spark/versions.yaml
=> [spark] Docker images updates - 2024-01-18-101638

docker/hydra/2/debian11/2.1/Dockerfile, docker/hydra/templates/Dockerfile.template
=> Docker - Hydra - CA-certificates added into image

docker/hazelcast/5/debian11/hazelcast-mc/5.3/Dockerfile, docker/hazelcast/templates/hazelcast-mc5/Dockerfile.template
=> Docker - Hazelcast - CA-certificates added

docker/c2d-debian/12/debian12/Dockerfile, docker/c2d-debian/templates/debian12/Dockerfile.template
=> Docker - c2d-debian - CA-certificates added into debian11 and debian12

docker/tikv/6/debian11/6.5/Dockerfile, docker/tikv/templates/Dockerfile.template
=> Docker - Tikv - Added ca-certificates

docker/prometheus-operator/0/debian11/0.65/Dockerfile, docker/prometheus-operator/0/debian11/0.68/Dockerfile, docker/prometheus-operator/templates/Dockerfile.template
=> Docker - Prometheus-operator - GOlang version updated to 1.21.6

k8s/prometheus/Makefile
=> k8s - Prometheus - Added track 2.49

docker/jaeger-operator/1/debian11/1.53/Dockerfile, docker/jaeger-operator/versions.yaml
=> Docker - Jaeger-operator version updated to 1.53.0 and goland to 1.20

docker/knative/1/debian11/1.10/Dockerfile, docker/knative/1/debian11/1.13/Dockerfile, docker/knative/1/debian11/1.9/Dockerfile, docker/knative/versions.yaml
=> Docker - Knative version updated to 1.13.0

docker/airflow/2/debian11/2.6/Dockerfile, docker/airflow/2/debian11/2.6/scripts/docker/install_airflow.sh, docker/airflow/2/debian11/2.8/Dockerfile, docker/airflow/2/debian11/2.8/scripts/docker/install_airflow.sh, docker/airflow/templates/Dockerfile.template, docker/airflow/templates/scripts/docker/install_airflow.sh
=> Docker - Airflow - Fix dependency for 2.8.2

k8s/spark/Makefile
=> k8s - Spark updated to track 3.5

docker/prometheus-operator/0/debian11/0.65/Dockerfile, docker/prometheus-operator/0/debian11/0.74/Dockerfile, docker/prometheus-operator/templates/Dockerfile.template, docker/prometheus-operator/versions.yaml
=> Docker - Prometheus-Operator - Bump to 0.74

k8s/nginx/Makefile
=> K8s - NGINX - Bump to 1.26

vm/chef/cookbooks/docker/attributes/default.rb, vm/chef/cookbooks/docker/recipes/compose.rb, vm/chef/cookbooks/redash/files/redash-setup
=> VM - Redash - Upgrade docker-compose and fix setup

.github/workflows/label.yml
=> Revert #1080 on label action

docker/spark/3/debian12/3.5/Dockerfile, docker/spark/templates/3/Dockerfile.template
=> Docker - Spark - Upgrade Zookeeper

k8s/spark/Makefile
=> K8s - Spark - Update metrics driver to gcp logging

k8s/cassandra/Makefile
=> K8s - Cassandra - Metrics_Exporter updated to v0.11.1-gke.1

docker/gitea/1/debian12/1.22/Dockerfile, docker/gitea/templates/Dockerfile.template
=> Docker - Gitea - Add git

docker/prometheus-operator/0/debian12/0.69/Dockerfile, docker/prometheus-operator/0/debian12/0.77/Dockerfile, docker/prometheus-operator/versions.yaml
=> Docker - Prometheus-operator - BUMP to 0.77.1 and debian12

docker/harbor/2/debian11/2.10/Dockerfile, docker/harbor/2/debian11/2.7/Dockerfile, docker/harbor/2/debian12/2.11/Dockerfile, docker/harbor/2/debian12/2.7/Dockerfile, docker/harbor/versions.yaml
=> Docker - Harbor - BUMP to version 2.11.1

k8s/consul/Makefile
=> K8s - Consul - BUMP to track 1.19

k8s/influxdb/Makefile
=> K8s - InfluxDB - Upgrade prometheus-to-sd container

vm/chef/cookbooks/cassandra/attributes/default.rb
=> VM - Cassandra - Bump to 4.1.7

.github/CODEOWNERS
=> VM - Allow @c2d-contributors team to upgrade VM versions

vm/chef/cookbooks/cassandra/attributes/default.rb
=> [cassandra] VM images updates - 2024-11-08-093759

vm/chef/cookbooks/dreamfactory/attributes/default.rb
=> [dreamfactory] VM images updates - 2024-11-08-093844

vm/chef/cookbooks/haproxy/attributes/default.rb
=> [haproxy] VM images updates - 2024-11-08-093901

vm/chef/cookbooks/kafka/attributes/default.rb
=> [kafka] VM images updates - 2024-11-08-093926

vm/chef/cookbooks/mautic/attributes/default.rb
=> [mautic] VM images updates - 2024-11-08-093952

vm/chef/cookbooks/nodejs/attributes/default.rb
=> [nodejs] VM images updates - 2024-11-08-094017

vm/chef/cookbooks/nginx/attributes/default.rb
=> [nginx] VM images updates - 2024-11-08-094009

vm/chef/cookbooks/prestashop/attributes/default.rb
=> [prestashop] VM images updates - 2024-11-08-094037

vm/chef/cookbooks/solr/attributes/default.rb
=> [solr] VM images updates - 2024-11-08-094110

vm/chef/cookbooks/redmine/attributes/default.rb
=> [redmine] VM images updates - 2024-11-08-094102

vm/chef/cookbooks/influxdb/attributes/default.rb
=> [influxdb] VM images updates - 2024-11-08-093909

vm/chef/cookbooks/ghost/attributes/default.rb
=> [ghost] VM images updates - 2024-11-08-093853

vm/chef/cookbooks/dokuwiki/attributes/default.rb, vm/chef/cookbooks/dokuwiki/recipes/default.rb
=> [dokuwiki] VM images updates - 2024-11-08-093834

vm/chef/cookbooks/joomla/attributes/default.rb
=> [joomla] VM images updates - 2024-11-08-093917

vm/chef/cookbooks/mattermost/attributes/default.rb
=> [mattermost] VM images updates - 2024-11-08-093944

vm/chef/cookbooks/moodle/attributes/default.rb
=> [moodle] VM images updates - 2024-11-08-094000

vm/chef/cookbooks/odoo/attributes/default.rb
=> [odoo] VM images updates - 2024-11-08-094028

vm/chef/cookbooks/redis/attributes/default.rb
=> [redis] VM images updates - 2024-11-08-094054

vm/chef/cookbooks/weblate/attributes/default.rb
=> [weblate] VM images updates - 2024-11-08-094127

vm/chef/cookbooks/odoo/attributes/default.rb
=> VM - Odoo - sha256sum changed for odoo 18.0

vm/chef/cookbooks/odoo/attributes/default.rb
=> VM - Odoo - Updated sha256 checksum for odoo_18.0.20241107.tar.xz

docker/activemq/versions.yaml, docker/airflow/versions.yaml, docker/argo-workflows/versions.yaml, docker/c2d-debian/versions.yaml, docker/cert-manager/versions.yaml, docker/django/versions.yaml, docker/drupal/versions.yaml, docker/falco/versions.yaml, docker/gitea/versions.yaml, docker/gitlab/versions.yaml, docker/harbor/versions.yaml, docker/kafka/versions.yaml, docker/keycloak/versions.yaml, docker/prometheus-operator/versions.yaml, docker/solr/versions.yaml, docker/spark/versions.yaml, docker/superset/versions.yaml, docker/zookeeper/versions.yaml
=> Docker - Add service annotations to containers

vm/chef/cookbooks/zabbix/attributes/default.rb
=> [zabbix] VM images updates - 2024-11-08-094136

docker/c2d-debian/versions.yaml
=> Docker - Debian - Add latest tag to debian11

vm/chef/cookbooks/liferay/attributes/default.rb, vm/tests/solutions/spec/liferay/liferay_spec.rb
=> [liferay] VM images updates - 2024-11-08-093935

docker/gitlab/17/debian12/17.5/Dockerfile, docker/gitlab/templates/Dockerfile.template
=> Docker - Gitlab - Fix typo

cloudbuild-k8s.yaml, k8s/c2d_deployer.Makefile, k8s/wordpress/Makefile
=> K8s - Allow crane binary to be set

k8s/activemq/Makefile, k8s/activemq/apptest/tester/Dockerfile
=> K8s - ActiveMQ - Add annotations

k8s/argo-workflows/Makefile, k8s/argo-workflows/apptest/tester/Dockerfile
=> K8s - Argo-Workflows - Add annotations

k8s/cert-manager/Makefile, k8s/cert-manager/apptest/tester/Dockerfile
=> K8s - Cert-Manager - Add annotations

k8s/consul/Makefile, k8s/consul/apptest/tester/Dockerfile
=> K8s - Consul - Add annotations

k8s/django/Makefile, k8s/django/apptest/tester/Dockerfile
=> K8s - Django - Add annotations

k8s/drupal/Makefile, k8s/drupal/apptest/tester/Dockerfile, k8s/drupal/apptest/tester/tests/common/drupal-suite.yaml, k8s/drupal/apptest/tester/tests/external/drupal-external-suite.yaml, k8s/drupal/chart/drupal/templates/drupal-statefulset.yaml, k8s/drupal/chart/drupal/templates/mariadb-secret.yaml, k8s/drupal/chart/drupal/templates/mariadb-statefulset.yaml
=> K8s - Drupal - Add annotations

k8s/falco/Makefile, k8s/falco/apptest/tester/Dockerfile, k8s/falco/apptest/tester/tests/basic-suite.yaml
=> K8s - Falco - Add annotations

k8s/gitea/Makefile, k8s/gitea/apptest/tester/Dockerfile
=> K8s - Gitea - Add annotations

k8s/influxdb/Makefile, k8s/influxdb/apptest/tester/Dockerfile
=> K8s - InfluxDB - Add annotations

k8s/joomla/Makefile, k8s/joomla/apptest/tester/Dockerfile
=> K8s - Joomla - Add annotations

k8s/mariadb/Makefile, k8s/mariadb/apptest/tester/Dockerfile
=> K8s - MariaDB - Add annotations

k8s/prometheus/Makefile, k8s/prometheus/apptest/tester/Dockerfile
=> K8s - Prometheus - Add annotations

k8s/solr/Makefile, k8s/solr/apptest/tester/Dockerfile
=> K8s - Solr - Add annotations

k8s/spark/Makefile, k8s/spark/apptest/tester/Dockerfile
=> K8s - Spark - Add annotations

k8s/nginx/Makefile, k8s/nginx/apptest/tester/Dockerfile
=> K8s - NGINX - Add annotations

k8s/postgresql/Makefile, k8s/postgresql/apptest/tester/Dockerfile
=> K8s - PostgreSQL - Add annotations

k8s/cassandra/Makefile, k8s/cassandra/apptest/tester/Dockerfile, k8s/cassandra/apptest/tester/tests/basic-suite.yaml
=> K8s - Cassandra - Add annotations

k8s/kafka/Makefile, k8s/kafka/apptest/tester/Dockerfile
=> K8s - Kafka - Add annotations

k8s/prometheus-operator/Makefile, k8s/prometheus-operator/apptest/tester/Dockerfile
=> K8s - Prometheus Operator - Add annotations

k8s/rabbitmq/Makefile, k8s/rabbitmq/apptest/tester/Dockerfile
=> K8s - RabbitMQ - Add annotations

k8s/gitlab/Makefile, k8s/gitlab/apptest/tester/Dockerfile
=> K8s - Gitlab - Add annotations

.github/CODEOWNERS
=> Remoke c2d-contributors team ownership

k8s/falco/Makefile
=> K8s - Falco - Bump exporter to 0.8

k8s/c2d_deployer.Makefile
=> K8s - Replace service annotation key

tools/cloudbuild-dockertools.yaml
=> Disable release creation for the versioning tools

docker/zookeeper/3/debian12/3.8/Dockerfile, docker/zookeeper/3/debian12/3.9/Dockerfile, docker/zookeeper/templates/zookeeper/Dockerfile.template, docker/zookeeper/versions.yaml
=> Docker - Zookeeper - Fix vulnerabilities

k8s/superset/Makefile
=> [K8s] Superset k8s solution upgrade du-k8s-superset-16072025
