k8s/jenkins/manifest/manifests.yaml.template
Commit originally came from https://github.com/GoogleCloudPlatform/click-to-deploy/pull/209 - creating a separate pull request to trigger cloudbuild integration.
* Google and contributors of this project do not affiliate with comments from #209.
* Updating Jenkins terminology to be more inclusive and consistent with Jenkins [intended naming convention](https://issues.jenkins-ci.org/browse/JENKINS-42816).
Fixes #209.
=> Use "agent" instead of "slave"

k8s/airflow-operator/README.md, k8s/cassandra/README.md, k8s/elastic-gke-logging/README.md, k8s/elasticsearch/README.md, k8s/grafana/README.md, k8s/influxdb/README.md, k8s/jenkins/README.md, k8s/memcached/README.md, k8s/nginx/README.md, k8s/postgresql/README.md, k8s/prometheus/README.md, k8s/rabbitmq/README.md, k8s/sample-app/README.md, k8s/spark-operator/README.md, k8s/wordpress/README.md
This PR is a follow up to #254 and #277. `BEGINFILE` is supported only in [`gawk`](https://www.gnu.org/software/gawk/manual/html_node/BEGINFILE_002fENDFILE.html) and `FNR==1` is compatible across different implementations, including `gawk` and `nawk`. Read more [here](https://www.gnu.org/software/gawk/manual/html_node/Other-Versions.html#Other-Versions).
=> Replace gawk-specific feature of BEGINFILE with nawk compatible FNR==1

k8s/influxdb/apptest/tester/tests/basic-suite.yaml.template, k8s/nginx/apptest/tester/tests/basic-suite.yaml.template
After 0.7.5 release, the framework is cares about it instead of us.
https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/releases/tag/0.7.5
=> Remove STS readiness.

vm/chef/cookbooks/cassandra/attributes/default.rb
Cassandra has been updated to 3.11.4 [upstream](http://dl.bintray.com/apache/cassandra/dists/311x/main/binary-amd64/Packages). Updating this attribute so the image can be built again.
=> Bump cassandra version to 3.11.4

vm/chef/cookbooks/kafka/attributes/default.rb
Kafka has been updated [upstream](https://www-us.apache.org/dist/kafka/2.1.1/). Updating this attribute so the image will build successfully.
=> Bump kafka version to 2.1.1

k8s/grafana/apptest/tester/tests/basic-suite.yaml
**Category:**
---
Issue:
[K8s][Grafana]the application sets the status to ready too early #367
=> Grafana issue

.github/ISSUE_TEMPLATE/docker_issue_template.md, .github/ISSUE_TEMPLATE/k8s_issue_template.md, .github/ISSUE_TEMPLATE/vm_issue_template.md
**Category:**
---
1.    The label `needs-triage` means **"This wasn't investigate by the repo's owners yet"**.
The idea is to assigne this label to all new issues, to notice that
repo's owners haven't investigate the issue yet.
After the investigation, the label should be dropped.
1.   Additionally, the `kind/` prefix has been added. Thanks to this, it's much easier to apply labels.
=> Add "needs-triage" tag. Add "kind" prefix

k8s/elastic-gke-logging/Makefile, k8s/elasticsearch/Makefile
It seems like `marketplace.gcr.io` for Ubuntu has been changed. The new address is http://marketplace.gcr.io/google/ubuntu1604:latest.
=> Update Ubuntu gcr.io

k8s/cassandra/schema.yaml, k8s/elasticsearch/schema.yaml, k8s/jenkins/schema.yaml, k8s/mariadb/schema.yaml, k8s/postgresql/schema.yaml, k8s/rabbitmq/schema.yaml, k8s/sonarqube/schema.yaml
Cassandra, Elastic GKE Logging and Elasticsearch have
`updateStrategy=OnDelete`, so I'm going to disabled the support for now.
=> Enabled/disabled kalm supported.

vm/chef/cookbooks/percona/files/percona-setup, vm/chef/cookbooks/percona/recipes/default.rb
**Category:**
---
The addition of the percona-toolkit install broke the deployment due to missing dependencies. Adding dependency download and install to allow for offline install. Addresses #660
=> Add dependencies for percona-toolkit

.travis.yml, Makefile, scripts/cloudbuild_k8s_generator.py, scripts/cloudbuild_k8s_generator_test.py, scripts/triggers_vm_generator.py, scripts/triggers_vm_generator_test.py
Generates GCB triggers configuration automatically based on Chef's cookbooks dependencies. For now, it will be just printed until triggers as a code are not supported.
Output: https://travis-ci.com/GoogleCloudPlatform/click-to-deploy/jobs/218598730
=> [Makefile] Add vm-generate-triggers target

vm/chef/cookbooks/wordpress-ha/attributes/default.rb
=> Bump wordpress-ha to latest, wp-stateless to 2.2.7

k8s/cassandra/Makefile, k8s/elastic-gke-logging/Makefile, k8s/elasticsearch/Makefile, k8s/grafana/Makefile, k8s/influxdb/Makefile, k8s/jenkins/Makefile, k8s/mariadb/Makefile, k8s/memcached/Makefile, k8s/nginx/Makefile, k8s/postgresql/Makefile, k8s/rabbitmq/Makefile, k8s/sonarqube/Makefile, k8s/wordpress/Makefile
```
---- REGISTRY = gcr.io/XXX
---- GCS_URL = gs://XXX
---- NAMESPACE = default
---- TRACK = 5.3
---- RELEASE = 5.3.4-20190913-181758
---- MARKETPLACE_TOOLS_TAG = 0.8.0-alpha06
---- APP_GCS_PATH = gs://XXX/grafana-managed-updates/5.3
---- APP_DEPLOYER_IMAGE = gcr.io/XXX/grafana-managed-updates/deployer:5.3.4-20190913-181758
docker run --rm --entrypoint=cat marketplace.gcr.io/google/grafana5@sha256:987e44b3425d4e80061b7a33ace1bc3a9575f033e017e5b3f48144b39d228811 /usr/share/grafana/VERSION
5.3.4
---- REGISTRY = gcr.io/XXX
---- GCS_URL = gs://XXX
---- NAMESPACE = default
---- TRACK = 3.11
---- RELEASE = 3.11.4-20190913-181839
---- MARKETPLACE_TOOLS_TAG = 0.8.0-alpha06
---- APP_GCS_PATH = gs://XXX/cassandra-managed-updates/3.11
---- APP_DEPLOYER_IMAGE = …
```
=> Release 13.09.2019

vm/chef/cookbooks/elasticsearch/attributes/default.rb, vm/chef/cookbooks/elasticsearch/files/elasticsearch, vm/chef/cookbooks/elasticsearch/recipes/default.rb
Elasticsearch has xpacks included as of version 6.3 and the cookbooks needed to be changed to remove the download/install of xpacks.
=> Bump Elasticsearch to 7.3.2

k8s/prometheus/Makefile, k8s/prometheus/README.md
All P+G images with tag 2.2 are gone and the latest ones are with tag 2.11.
=> Bump the images version for P+G: 2.2->2.11

k8s/neo4j-ce/README.md
Storage class variable was initially referenced as `NEO4J_STORAGE_CLASS` in the export command but was referenced only as `STORAGE_CLASS` in the helm template command.
=> Made storage class variable name consistent

vm/chef/cookbooks/wordpress/files/wordpress-setup
* Theme in master is not packaged by default in WP `twentyseventeen`, which now it's `twentytwentyone` .
* Removing fixed theme, and leaving the default one packaged by WP.
* Minor refactoring
=> VM - WordPress - Use default WP theme instead of a fixed one.

docker.Dockerfile
=> Use same bazel version as runtime-commons

.github/workflows/ci-tests.yaml, Makefile, vm/chef/.rubocop.yml, vm/chef/cookbooks/apache2/resources/allow_override.rb, vm/chef/cookbooks/c2d-config/resources/c2d_startup_script.rb, vm/chef/cookbooks/mysql/recipes/install-and-configure-mysqld.rb, vm/chef/cookbooks/mysql/recipes/install-and-configure-mysqld8.rb, vm/chef/cookbooks/nginx/recipes/stretch-backports.rb, vm/chef/cookbooks/nodenvm/resources/npm.rb, vm/chef/cookbooks/nodenvm/resources/run.rb, vm/chef/cookbooks/openjdk11/recipes/default.rb, vm/tests/solutions/.rubocop.yml
* `chefdk` official container no longer available
* https://www.chef.io/blog/goodbye-chefdk-hello-chef-workstation
* https://hub.docker.com/r/chef/chefdk
* `foodcritic` deprecated
* https://blog.chef.io/goodbye-foodcritic/
* output: 
```
Foodcritic has been deprecated. Use cookstyle instead, which provides over 200 Chef Infra cops with autocorrection! For more details see https://blog.chef.io/goodbye-foodcritic/
```
=> VM - Fix chefdk and foodcritic deprecation

docker/keycloak/18/debian11/18.0/Dockerfile, docker/keycloak/templates/Dockerfile.template, docker/keycloak/versions.yaml
Use the patched h2 database from the debian security-stable repo.
=> Docker - Keycloak - patch h2database

docker/gogs/0/debian11/0.12/entrypoint.sh, docker/gogs/0/debian11/0.12/run_test.sh, docker/gogs/README.md, docker/gogs/templates/entrypoint.sh, docker/gogs/templates/run_test.sh
```
DEPLOYER SMOKE_TEST + testrunner -logtostderr --test_spec=/tests/gogs.yaml
DEPLOYER SMOKE_TEST I1010 10:52:08.626105       7 main.go:86] >>> Running /tests/gogs.yaml
DEPLOYER SMOKE_TEST I1010 10:52:08.627005       7 main.go:136]  >   0: kubectl smoke test
DEPLOYER SMOKE_TEST I1010 10:52:08.689770       7 main.go:141]  PASSED
DEPLOYER SMOKE_TEST I1010 10:52:08.689905       7 main.go:136]  >   1: Wait for the webserver get ready
DEPLOYER SMOKE_TEST I1010 10:52:08.996756       7 main.go:141]  PASSED
DEPLOYER SMOKE_TEST I1010 10:52:08.996787       7 main.go:136]  >   2: Try to run test
DEPLOYER SMOKE_TEST I1010 10:52:09.654059       7 main.go:141]  PASSED
DEPLOYER SMOKE_TEST I1010 10:52:09.654216       7 main.go:117]  >> Summary: PASSED
DEPLOYER SMOKE_TEST I1010 10:52:09.654274       7 …
```
=> Docker - Gogs - Fix entrypoint

k8s/joomla/README.md, k8s/joomla/apptest/tester/Dockerfile, k8s/joomla/apptest/tester/tests/common/joomla-suite.yaml, k8s/joomla/apptest/tester/tests/external/exporter-external-suite.yaml, k8s/joomla/apptest/tester/tests/external/joomla-external-suite.yaml, k8s/joomla/chart/joomla/templates/_helpers/pods.tpl, k8s/joomla/chart/joomla/templates/joomla-statefulset.yaml
```
DEPLOYER SMOKE_TEST I0307 10:57:03.787148       7 main.go:86] >>> Running /tests/common/db-suite.yaml
DEPLOYER SMOKE_TEST I0307 10:57:03.788461       7 main.go:136]  >   0: Connect to a database (as root user)
DEPLOYER SMOKE_TEST I0307 10:57:03.829860       7 main.go:141]  PASSED
DEPLOYER SMOKE_TEST I0307 10:57:03.829896       7 main.go:136]  >   1: Can connect to a database (as joomla user)
DEPLOYER SMOKE_TEST I0307 10:57:03.852797       7 main.go:141]  PASSED
DEPLOYER SMOKE_TEST I0307 10:57:03.852830       7 main.go:136]  >   2: Can not connect to a database with incorrect credentials
DEPLOYER SMOKE_TEST I0307 10:57:03.875579       7 main.go:141]  PASSED
DEPLOYER SMOKE_TEST I0307 10:57:03.875602       7 main.go:136]  >   3: Can not connect to a database without credentials
DEPLOYER …
```
=> K8S - Joomla - Fix tests, add checkdb step

k8s/neo4j-ce/Makefile, k8s/neo4j-ce/README.md, k8s/neo4j-ce/apptest/deployer/neo4j-ce/templates/tester.yaml, k8s/neo4j-ce/apptest/tester/Dockerfile
```
+ shopt -s nullglob
+ for test in /tests/*
+ testrunner -logtostderr --test_spec=/tests/cli-suite.yaml
I0313 14:44:16.430112       7 main.go:86] >>> Running /tests/cli-suite.yaml
I0313 14:44:16.433080       7 main.go:136]  >   0: Bad authentication via CLI
I0313 14:44:17.705928       7 main.go:141]  PASSED
I0313 14:44:17.705953       7 main.go:136]  >   1: Create a node via CLI
I0313 14:44:21.139506       7 main.go:141]  PASSED
I0313 14:44:21.139530       7 main.go:136]  >   2: Get nodes via CLI
I0313 14:44:22.515858       7 main.go:141]  PASSED
I0313 14:44:22.515936       7 main.go:117]  >> Summary: PASSED
I0313 14:44:22.515944       7 main.go:123]  >   0: Bad authentication via CLI: PASSED
I0313 14:44:22.515963       7 main.go:123]  >   1: Create a node via CLI: PASSED
I0313 …
```
=> K8S - Neo4j - Fix chart, update version

k8s/prometheus/chart/prometheus/templates/_helpers.tpl, k8s/prometheus/chart/prometheus/templates/alertmanager-statefulset.yaml, k8s/prometheus/chart/prometheus/templates/prometheus-statefulset.yaml, k8s/redis-ha/chart/redis-ha/templates/_helpers.tpl
Can't publish these solutions now, errors are:
```
56s         
Warning   
ProvisioningFailed     
persistentvolumeclaim/apptest-7usca8m9-redis-ha-data-apptest-7usca8m9-redis-ha-server-0   failed to provision volume with StorageClass "apptest-7usca8m9-apptest-7usca8m9-redis-persistence-storageclass": rpc error: code = InvalidArgument desc = CreateVolume failed to create single zonal disk pvc-07381310-7eba-437b-896b-407d82eafee2: failed to insert zonal disk: unknown Insert disk error: googleapi: Error 400: Invalid value for field 'resource.labels': ''. Label value 'apptest-7usca8m9-redis-ha-data-apptest-7usca8m9-redis-ha-server-0' violates format constraints. The value can only contain lowercase letters, numeric characters, underscores and dashes. The value can be at most 63 characters …
```
=> K8S -Prometheus, Redis-ha - Add statefulsets name constraints

k8s/hydra/README.md, k8s/hydra/chart/hydra/templates/postgresql-statefulset.yaml, k8s/hydra/chart/hydra/values.yaml, k8s/hydra/schema.yaml
```
DEPLOYER SMOKE_TEST I0413 11:26:59.745454       7 main.go:86] >>> Running /tests/basic-suite.yaml
DEPLOYER SMOKE_TEST I0413 11:26:59.746247       7 main.go:136]  >   0: Hydra Liveness Check
DEPLOYER SMOKE_TEST I0413 11:26:59.787987       7 main.go:141]  PASSED
DEPLOYER SMOKE_TEST I0413 11:26:59.788023       7 main.go:136]  >   1: Hydra Readiness Check
DEPLOYER SMOKE_TEST I0413 11:26:59.814225       7 main.go:141]  PASSED
DEPLOYER SMOKE_TEST I0413 11:26:59.814255       7 main.go:136]  >   2: Is Hydra /metrics/prometheus HTTP endpoint working for Prometheus metrics
DEPLOYER SMOKE_TEST I0413 11:26:59.856037       7 main.go:141]  PASSED
DEPLOYER SMOKE_TEST I0413 11:26:59.856064       7 main.go:117]  >> Summary: PASSED
DEPLOYER SMOKE_TEST I0413 11:26:59.856068       7 main.go:123]  >   0: …
```
=> K8S - Hydra - Fix psql statefulset

k8s/cassandra/apptest/tester/Dockerfile, k8s/cassandra/chart/cassandra/templates/cassandra-statefulset.yaml
```
I0419 10:32:27.639288       6 main.go:86] >>> Running /tests/basic-suite.yaml
I0419 10:32:27.640221       6 main.go:136]  >   0: There are exactly 3 nodes in a cluster
I0419 10:32:27.952913       6 main.go:141]  PASSED
I0419 10:32:27.953153       6 main.go:136]  >   1: Execute CQL query
I0419 10:32:37.377866       6 main.go:141]  PASSED
I0419 10:32:37.377968       6 main.go:136]  >   2: Cluster is connected
I0419 10:32:48.107007       6 main.go:141]  PASSED
I0419 10:32:48.107038       6 main.go:136]  >   3: Can read/write data between nodes
I0419 10:33:02.702186       6 main.go:141]  PASSED
I0419 10:33:02.702242       6 main.go:136]  >   4: Prometheus metrics are exported
I0419 10:35:31.024722       6 main.go:141]  PASSED
I0419 10:35:31.024820       6 main.go:117]  >> Summary: PASSED …
```
=> K8S - Cassandra - Update probes, fix hardcoded cluster seeds

k8s/jaeger-operator/Makefile, k8s/jaeger-operator/apptest/tester/Dockerfile
=> K8s - Jaeger Operator - Add annotations

k8s/cassandra/chart/cassandra/templates/cassandra-statefulset.yaml
Fix for #2863 
Update cassandra/templates/cassandra-statefulset to use `monitored-resource-type-prefix`
=> Update cassandra/templates/cassandra-statefulset to use monitored-resource-type-prefix
